### ISSUE TITLE
Broken link: Quick setup of Jitsi meet using docker link leads back to the same page

### ISSUE THREAD

**Issue by axelsimon** [RocketChat/docs-old#100]
Hi,
Just to let you know, on the page https://rocket.chat/docs/administrator-guides/jitsi-video-bridge/ at the end of the page, the link in "Also, please consult our guide to **quick setup of Jitsi Meet servers stack via Docker image**." just leads back to the same page (https://rocket.chat/docs/administrator-guides/jitsi-video-bridge/) and not to the actual guide.

**Comment by amkgo** [comment]
Please add the instruction on how to integrate Jitsi-video-bridge Docker image and Rocket.Chat docker image on the same server.

Thanks.

**Comment by girlandhercode** [comment]
It would be immensely helpful to have the actual link to this guide.  Any help is appreciated. Thanks in advance!

**Comment by asshewale** [comment]
Hi @axelsimon @amkgo @girlandhercode , I have integrated the Jitsi in Rocket chat we have both things on same server, but my problem is suppose two users are chating and one user initiates the video call to other user  (for this video call jitsi SDK has been used) how other user will come to know that he is getting the video call, WIll any one please help me for this.

**Comment by fliptrail** [comment]
That page does not exist now
