### ISSUE TITLE
Possible patched install maintain instructions

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/docs-old#1014]
Copying instructions shared by @ohmonster 

> For my patch and develpoment sanity I
> * maintain my custom code in a forked repo on github, in its own branch
> * use local virtual machines for development and staging/sandbox tasks
> * to have good development data, update my meteor mongodb instance with dump of production data (not necessarily recent -- it's just good to have users, channels, and the settings in place)
> * put some version of prod data onto the staging/sandbox server for the same reason 
> 
> then, for staying current with the official project and deploying my patch
> * deploy and verify that any new official release works with our existing config files on a staging/sandbox virtual
> * rebase my fork's develop and master branches from the official rocketchat project 
> * rebase my fork's patch branch on the master branch of the official project
> * use meteor to make a production bundle
> * deploy and verfiy the resulting bundle on a staging/sandbox virtual
> * deploy my patched bundle to production
> 
> for any of the "deploy" items, I use the instructions in the manual installation section. 

May be of use as basis for someone to create a doc on how to do such.

**Comment by Rodriq** [comment]
@geekgonecrazy Please can you confirm if this is of any relevance again?
We have docs on setting up development environment here https://developer.rocket.chat/rocket.chat/rocket.chat-server

**Comment by geekgonecrazy** [comment]
Probably not.  At this point very out dated at very least
