### ISSUE TITLE
Typo in developer guides internationalization section

### ISSUE THREAD

**Issue by pranay414** [RocketChat/docs-old#1021]
In [https://rocket.chat/docs/developer-guides/internationalization/](https://rocket.chat/docs/developer-guides/internationalization/) there is a typo in introductory paragraph `When developing in Rocket.Chat, you have the ablilty to add strings to our tranlations files in wich later will be tranlsated to other languages by our community translators.` It should be `translations files`.

**Comment by MartinSchoeler** [comment]
Closed by #1022
