### ISSUE TITLE
Dead Simple Screen Sharing Problem 

### ISSUE THREAD

**Issue by jolio007** [RocketChat/docs-old#1027]
I did the whole dead simple screen integration. I followed everything and it does give a meeting that one can join. However, when 2 people click on the link none of them can share their screen. I tested it. When I click on the link, there's the option to share the screen but I'm not set as a "presenter" so whoever click on the link cannot see whatever I'm sharing. When a person click on the link, they can't see anyone online

**Comment by dudanogueira** [comment]
Looks like the endpoint for this integration is no longer available, and the access to API is paid only.

Doc: https://docs.rocket.chat/guides/administration/admin-panel/integrations/deadsimplescreensharing
Service: https://deadsimplescreensharing.com/
related link: https://deadsimplescreensharing.com/rocket-chat-integration
