### ISSUE TITLE
OAuth gitlab How do I configure scope=api?

### ISSUE THREAD

**Issue by benxiaohai1212** [RocketChat/docs-old#1031]
redirect url 
> http://gitlab.net.cn/oauth/authorize?client_id=4e06617e5a72a65130a3f999ab71dd09277804bd318ed2f2c0d5ba20344b3cc6&redirect_uri=http://rocketchat.net.cn/_oauth/gitlab?close&response_type=code&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJTUVp6a1lpX2hLRE9wMEc2VldoUWROZEVWVkdQT2h3UGk1R0UzXzNLMGQyIiwiaXNDb3Jkb3ZhIjpmYWxzZX0=&scope=read_user

gitlab report errors
```
An error has occurred
The requested scope is invalid, unknown, or malformed.
```

**Comment by Rodriq** [comment]
An updated doc here https://docs.rocket.chat/guides/administration/settings/oauth/gitlab-oauth-setup describes how to archive GitLab OAuth
