### ISSUE TITLE
End-to-end encryption technical documentation

### ISSUE THREAD

**Issue by john-light** [RocketChat/docs-old#1052]
I see that there is documentation for the user-facing aspect of activating and using end-to-end encryption. But I would also like to see technical documentation for the end-to-end encryption implementation, such as which algorithms are used, how the keys are generated (i.e. entropy source), and other technical details so as a user I can better assess the security of this implementation.

**Comment by makibras** [comment]
this has been added to the docs: https://docs.rocket.chat/guides/security/end-to-end-encryption-algorithms
if you have any feedback, please let us know. and if you come across a potential security issue, please mail us at security@rocket.chat
