### ISSUE TITLE
Snap tips tricks and FAQ

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/docs-old#107]
I've been pinning commands as I find them in [#ubuntu-snap](https://demo.rocket.chat/channel/ubuntu-snap)

If for some reason you need to get the ubuntu-core image for an air gapped device:
`curl -X GET -H "Content-Type: application/json" -H "X-Ubuntu-Series: 16" -H "X-Ubuntu-Architecture: amd64" "https://search.apps.ubuntu.com/api/v1/snaps/details/ubuntu-core?channel=stable&confinement=strict"` Make sure to change the architecture if differs from amd64

---

`sudo systemctl restart snap.rocketchat-server.rocketchat-server` to restart the server

---

Updates occur automatically with snap. Usually within 6 hours of a new version being posted. If you want it quicker, type: `sudo snap refresh rocketchat-server`

---

Directories and purpose:
- Your actual snap files are copied to: `/var/lib/snapd/snaps` and they are mounted read only
- Your snap common directory is: `/var/snap/rocketchat-server/common/` file upload to disk, and database is stored here.
- Your snap data directory is `/var/snap/rocketchat-server/<version>` this is a versioned folder.

---

Proper way to remove previous revisions:
`snap remove --revision=35 rocketchat-server`

---

Ensure its actually running with: `sudo systemctl status snap.rocketchat-server.rocketchat-server.service

---

To see the logs from rocket.chat `sudo journalctl -u snap.rocketchat-server.rocketchat-server`
To see the logs from mongo `sudo journalctl -u snap.rocketchat-server.rocketchat-mongo`

---

Add tool in snap for debugging purposes

```
snapcraft prime
snap try prime --devmode
cp /usr/bin/toolX prime
snap run <snap.app> --shell
sudo ./toolX
```

---

To backup data incase of re-install or just for sanity sake
Making a copy of `/var/snap/rocketchat-server/common` will be enough to back up all data.

**Comment by Sing-Li** [comment]
Can't stand waiting for this  .... where is it ALREADY?!!

**Comment by geekgonecrazy** [comment]
@Sing-Li some snippets added above ^ 😉

**Comment by geekgonecrazy** [comment]
Added in via #110 will update that document going forward 👍
