### ISSUE TITLE
Migrating data from meteor mongo

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/docs-old#108]
From https://github.com/RocketChat/Rocket.Chat/issues/4734#issuecomment-256746427
## 

Any guide or advice we give will be away from using meteor to run in production.

My advice would be to export your database from the meteor mongo, and install rocket.chat using a recommended method.

To do this first make sure meteor is running. Then run: mongodump -h 127.0.0.1 --port 3001 -d meteor

It'll dump the database in a folder called dump.

Then install mongodb on your system. Please see the mongo section in one of our guides: https://rocket.chat/docs/installation/manual-installation/ubuntu/

Once Mongo is installed restore the data using: mongorestore -d meteor dump/meteor if you want to use a different database, you'd take this as your opportunity to change the database name. Replacing -d meteor with your desired database name.

Then follow the remainder of the guide on setting up Rocket.Chat.

**Comment by dandv** [comment]
Note that with recent versions of Mongo, `-d` generates this warning:

> the --db and --collection args should only be used when restoring from a BSON file. Other uses are deprecated and will not exist in the future; use --nsInclude instead
