### ISSUE TITLE
SlackBridge documentation out of date

### ISSUE THREAD

**Issue by nodje** [RocketChat/docs-old#1097]
Maybe I missed something but I really can't enable a Slackbridge using the official https://rocket.chat/docs/administrator-guides/import/slack/slackbridge

It just doesn't work this way in Slack any more, apparently.

I've seen some issues showing it's actually working for some users, so I'm looking forward to some direction on how to enable this precious feature!

Thanks

**Comment by Rodriq** [comment]
Hey @nodje maybe you should be more explicit with what is not going well for you. I'll help in better knowing what to handle.
 ` It just doesn't work` please tell us what you've done which step is having trouble?

**Comment by nodje** [comment]
Well, it's not like the guide is a huge manual, it's only two paragraphs.
As I said, Slack has changed and just doesn't work the way described in `http://rocketchat.github.io/docs/administrator-guides/import/slack/slackbridge/`:

```
To create a Custom Bot in Slack:

    Go to https://my.slack.com/apps/manage/custom-integrations
    At the top-right of your screen, click on Build
    Choose Legacy custom integrations
    Scroll down and click on “Set up a bot user”
    Click “Add Configuration”
    Pick a username for your Bot and click Add Bot Integration
    Copy the API Token, you’ll need it when setting up SlackBridge in Rocket.Chat
    Customize your bot the way you like it and click on Save Integration
```
 "Choose Legacy custom integrations" isn't possible anymore.

There's most probably an easy way around, but as I'm not familiar with Slack "App" I just can't find it.

**Comment by nodje** [comment]
As far as I can tell, the way it works now, is that you have to go to "https://api.slack.com/" click "start building" then you get to a feature full menu, and the closest thing I could find to "Legacy Custom Integration" was `Legacy: Workspace apps` (https://api.slack.com/legacy-workspace-apps).

But I wasn't able to get anything working down the line

**Comment by nodje** [comment]
Would be nice to know if this is a confirmed issue and if it will be worked on soon or not!

**Comment by dingonv** [comment]
Confirming what @nodje said. 
the instructions to go to Legacy Custom Integrations is no longer an option at slack. 

Updated instructions are required.
Any ideas @Rodriq  ?

**Comment by Rodriq** [comment]
Okay perfect I can try to check that out and if I get it working, I'll update the instructions.
