### ISSUE TITLE
Error serving docs

### ISSUE THREAD

**Issue by Rodriq** [RocketChat/docs-old#1102]
When
   `$ jekyll serve --incremental --safe` is run as per the documentation,
 Get the following.

![doc serving error](https://user-images.githubusercontent.com/39289592/53290427-ff10d180-37a3-11e9-9b6b-dab52dc24245.png)

**Comment by Davide95** [comment]
Your gems don't follow the versioning specified in the Gemfile.lock.
Try running in the git cloned repo:
1. `git pull`
2. `gem install bundler -v 1.16.2`
3. `bundle install`

If everything works fine, run
`bundle exec "jekyll serve --incremental --safe"`.

OT: if you want to try you can just simply execute `gem install concurrent-ruby -v 1.0.5` but I think it's not the only gem with a different version installed.

Let me know.

**Comment by Davide95** [comment]
@Rodriq can you please says if it's working now or not?
It's been 14 days since my reply and 23 days since your issue opening.
I don't think it's an issue with the build system and if you don't give us a feedback maybe it's a good idea to close the issue:)

**Comment by Rodriq** [comment]
yea @Davide95  i'll close it
