### ISSUE TITLE
LiveChat API / CURL

### ISSUE THREAD

**Issue by NiBOLT** [RocketChat/docs-old#1103]
I am getting the following results returned when using the CURL command to register a visitor, please can you advise on how this is resolved

![image](https://user-images.githubusercontent.com/45275040/53291186-4351a100-37a7-11e9-925c-ed2ecd4e930b.png)

Register Visitor  CURL Command

curl -X POST \
     -H "Content-type:application/json" \
     http://localhost:3000/api/v1/livechat/visitor \
    -d '{"visitor": {"name": Livechat Visitor, "email": "visitor@rocket.chat", "token": "iNKE8a6k6cjbqWhWd", "phone": "55 51 5555-5555", customFields": [{ "key": "address", "value": "Rocket.Chat street", "overwrite": true }] }'

**Comment by renatobecker-zz** [comment]
@NiBOLT, there are some JSON properties/values that are missing double quotes, like `Livechat Visitor`, `customFields"`..

Thanks.
