### ISSUE TITLE
Email configuration missing parameters

### ISSUE THREAD

**Issue by wcgcoder** [RocketChat/docs-old#1108]
The SMTP configuration page currently lacks the parameters for "pool" and "Ignore TLS."
[/administrator-guides/email/setup/README.md](https://github.com/RocketChat/docs/blob/master/administrator-guides/email/setup/README.md)

<img width="1200" alt="rc 0 74 1 smtp" src="https://user-images.githubusercontent.com/20342522/53436704-a4989080-39b0-11e9-8ea6-f320affc798f.png">

Thank you very much for your work on RC!

**Comment by codekhal** [comment]
May I take this issue!!
@wcgcoder

**Comment by wcgcoder** [comment]
@codekhal By all means! I don't have the time to dig up this portion of the code to document it. Thanks.

**Comment by codekhal** [comment]
![smpt](https://user-images.githubusercontent.com/32578541/53571670-7cb35380-3b8f-11e9-9d3a-611b7f79f779.png)

@wcgcoder Just to clear things out, do you want this snap to be added to the readme.md, so that "Pool" and "IgnoreTLS" could be visible. Is that so?

**Comment by wcgcoder** [comment]
I recommend also adding the required information to the list of configuration items in the text. This may require exploring the source and determining what the pooling is actually doing. Also, a coherent explanation of "IgnoreTLS" is required. Thanks.

**Comment by codekhal** [comment]
okay, I will talk to mentors in that case. Because it definitely makes sense to add relevant information about the configuration tools.

**Comment by wcgcoder** [comment]
Please reopen. 
The update is missing the update of the actual text with the description of the Pooling and TLS Ignore configuration options.
