### ISSUE TITLE
[BUG] Unable to enter text in search bar in documentation pages

### ISSUE THREAD

**Issue by fliptrail** [RocketChat/docs-old#1129]
Unable to enter text in search bar in documentation pages 

**Actual behavior**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40834245/54176348-7fc61200-44b4-11e9-9b97-fb9292fea7b7.gif)

Android version : 8.1 MIUI 10.2 Stable
Browser: Chrome 72

**Additional notes**
Someone else can take this up.

**Comment by Rodriq** [comment]
@fliptrail try leaving the specific path or link to where one can get started

**Comment by fliptrail** [comment]
This bug was happening on every page at Rocket.Chat/docs for example https://rocket.chat/docs/user-guides/connecting-to-a-server/ @Rodriq

**Comment by Rodriq** [comment]
@fliptrail okay yeah you're right. Ive seen it.
  Do you have any idea? or already working on it?

**Comment by fliptrail** [comment]
No, I am not working on it.

**Comment by Davide95** [comment]
Tested on Android P, latest version of Chrome.
Repeatedly clicking on the inputbox over a short period of time let you type into the input box.
Using Remote Devices on Chrome seems to exclude the possibility of JS errors raised by the browser.

**Comment by MartinSchoeler** [comment]
Fixed on https://github.com/RocketChat/docs/commit/ff3b813c5e379004b842bccb0388ac76e9b6744e
