### ISSUE TITLE
mongolab instructions outdated

### ISSUE THREAD

**Issue by valexa** [RocketChat/docs-old#1131]
Hi, mongolab was removed in 2015 https://www.ibm.com/blogs/bluemix/2015/10/mongodb-removal/ so the instructions at https://github.com/RocketChat/docs/blob/master/installation/paas-deployments/ibm-bluemix/README.md need to be updated

**Comment by Rodriq** [comment]
Here is the recent guide for IBM deployment https://docs.rocket.chat/quick-start/installing-and-updating/paas-deployments/ibm-cloud
Thanks. I think this should be closed.
