### ISSUE TITLE
Documentation missing for storing uploaded file in file system

### ISSUE THREAD

**Issue by Pratyush1197** [RocketChat/docs-old#1151]
In the File upload section of File system documentation is missing for the instructions to specify the path where the uploaded file be stored.

**Comment by Davide95** [comment]
You can find all the infos here: 
* https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/ (section "What folders do snaps use?").

If you're using another installation method just find [here](https://rocket.chat/docs/installation/manual-installation/) the path used  and then search for the `upload` folder.

It's documented, it is just different for each installation method and you have to find all the infos in the right section of the docs.

**Comment by ChristySujitha** [comment]
File system documentation - Please refer to these links:
https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/snaps
https://docs.rocket.chat/quick-start/deploying-rocket.chat/other-deployment-methods/manual-installation
https://docs.rocket.chat/guides/administration/admin-panel/settings/file-upload#filesystem
