### ISSUE TITLE
[UI/UX] Adding a button to page that will allow to scroll up the page

### ISSUE THREAD

**Issue by sudipt1999** [RocketChat/docs-old#1182]
![Screenshot from 2019-03-29 23-20-01](https://user-images.githubusercontent.com/38929617/55253297-fb78da80-527a-11e9-9f48-17b87132aaf5.png)

How about adding a button to page that will allow user to scroll up the page!

**Comment by MartinSchoeler** [comment]
I think adding such button would pollute even more the page, and the user can already select where he wants to go using the right table of contents.
