### ISSUE TITLE
[UI] table content data overflow

### ISSUE THREAD

**Issue by sudipt1999** [RocketChat/docs-old#1183]
![Screenshot from 2019-03-29 23-44-28](https://user-images.githubusercontent.com/38929617/55254029-df763880-527c-11e9-8860-dad01a4cf3d4.png)

The table content is overflow because the width is not large enough to hold it!

![Screenshot from 2019-03-29 23-45-20](https://user-images.githubusercontent.com/38929617/55254079-fe74ca80-527c-11e9-889a-573fec111875.png)

Setting the width of wrapper class to 100% will surely fix it I guess.

**Comment by MartinSchoeler** [comment]
Should be fixed when we set the docs to have a full-page width. Thanks for the bug report!
