### ISSUE TITLE
GraphQL Documentation needs to be updated

### ISSUE THREAD

**Issue by shiqimei** [RocketChat/docs-old#1187]
Hi, I found that package links are invalid in the bottom of the [GraphQL API Authentication](https://rocket.chat/docs/developer-guides/graphql-api/authentication/) of the GraphQL Documentation.

![image](https://user-images.githubusercontent.com/32427260/55272677-fd827e00-52fa-11e9-98bf-18ece21e70eb.png)

**Comment by lolimay** [comment]
I think I can contribute to this after understanding what Grant is 🙂
