### ISSUE TITLE
Update documentation about Permission

### ISSUE THREAD

**Issue by shiqimei** [RocketChat/docs-old#1191]
The latest Rocket.Chat supports about **90** permissions. But the current documentation only lists **76** items of the above. I will try to update this document in the next several hours or days. And learn these permissions at the same time 😉

**Comment by lolimay** [comment]
The 14 new permission rules are listed below:
1. `api-bypass-rate-limit`
2. `assign-roles`
3. `call-management`
4. `create-personal-access-tokens`
5. `leave-c`
6. `leave-p`
7. `manage-cloud`
8. `mention-here`
9. `remove-closed-livechat-rooms`
10. `reset-other-user-e2e-key`
11. `set-readonly`
12. `start-discussion`
13. `start-discussion-other-user`
14. `view-livechat-analytics`

**Comment by shiqimei** [comment]
Fixed in [#1192](https://github.com/RocketChat/docs/pull/1192)
