### ISSUE TITLE
How to make Interactive APIs documentation?

### ISSUE THREAD

**Issue by shiqimei** [RocketChat/docs-old#1193]
Hi, @MartinSchoeler !

If we are going to develop an interactive APIs documentation, which plan will we adapt to achieve this feature?
- One approach is that users need to deploy the Rocket.Chat server on their computer and run it locally. So that our Interactive APIs can connect to `http://localhost:3000` and return API testing results. But it seems not so user-friendly because users need to install the Rocket.Chat server first if they just want to test some API.
- Another way is we provide an APIs test server, and users can test the APIs in our documentation directly. But this will increase the extra server expense.

**Comment by Rodriq** [comment]
@lolimay  There are various ways it can be done.
  Either the `localhost`, `open.rocket.chat` servers or a `test server` like you said.
*This is a good discussion you can have with the mentors*
Think this issue should be closed
@MartinSchoeler @Sing-Li

**Comment by MartinSchoeler** [comment]
@lolimay Could you please move this to https://forums.rocket.chat/ ? We only use github for feature requests and bug reporting. Thanks!

**Comment by shiqimei** [comment]
> @lolimay Could you please move this to https://forums.rocket.chat/ ? We only use github for feature requests and bug reporting. Thanks!

OK, Got it!
