### ISSUE TITLE
Push notification guide is ambiguous or inaccurate. 

### ISSUE THREAD

**Issue by xenithorb** [RocketChat/docs-old#12]
https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/4.%20Administrator%20Guides/Push%20Notifications/README.md

By my testing, when the "Enable Gateway" setting is enabled, no further configuration of the server or client app are necessary. I did a packet trace of what it is doing and it literally sends everything off to the gateway server, and if it is configured with `https://rocket.chat` it works "out of the box" with the release .apk/client 

If you set the `GCP API Key` and `GCM Project Number` while using the Gateway, it doesn't seem to do anything, that is. I would imagine this is the point of having the privacy settings, since otherwise the entire message is sent to https://rocket.chat, so sensitive information could be leaked to the Rocket.Chat organization. 

If any only if you set `GCM API key` AND `GCM Project Number` AND set `Enable Gateway` to `false`, do you need to configure the Cordova client, I think.

**Comment by geekgonecrazy** [comment]
We have talked about a setup wizard.  We would make it clear there.  Also we are working on the ability to disable settings when a setting is checked.  So when gateway setting is checked we will disable the iOS and Android key entry.  To help re-inforce that.

**Comment by Rohlik** [comment]
@geekgonecrazy Any progress on wizard feature?

**Comment by geekgonecrazy** [comment]
Nothing yet.  A lot of other clean up happening and UI polish.

**Comment by MartinSchoeler** [comment]
@xenithorb We are no longer supporting the cordova app. Please try using the native apps. If you still have problems with notifications on the native apps, please open a new issue. Thanks!

**Comment by xenithorb** [comment]
Replace cordova client in the original issue with either/or native client and the issue still remains the same, correct?

The issue is not specific to the cordova app, but rather to any workflow that involves distributing apps with your own API keys (as it is the only way not to use your gateway AFAIK?)

This issue in its essence was more about documenting properly how to not use your push gateway.

**Comment by geekgonecrazy** [comment]
Agreed... We still need to document what the gateway is, why it's used, and if not using it what you need to do.  

I think since building the iOS and Android app does take developer experience of some sort.  We don't need to go into great detail.  But we do need to at the very least point in right direction

**Comment by geekgonecrazy** [comment]
https://docs.rocket.chat/guides/administrator-guides/notifications/push-notifications I think we forgot to close this one out.  But this guide is much more complete then it used to be.
