### ISSUE TITLE
Missing description 

### ISSUE THREAD

**Issue by kerolloz** [RocketChat/docs-old#1208]
there's a mistake in numbering the headers and missing description 
https://github.com/RocketChat/docs/blob/master/installation/manual-installation/ubuntu/snaps/README.md#4-copy-your-backup-file-to-a-different-system-for-safekeeping

**Comment by Rodriq** [comment]
> there's a mistake in numbering the headers and missing description
> https://github.com/RocketChat/docs/blob/master/installation/manual-installation/ubuntu/snaps/README.md#4-copy-your-backup-file-to-a-different-system-for-safekeeping

Please can you tell us what exactly is missing and what is required?
  It'll help in providing a better documentation about it.
