### ISSUE TITLE
[BUG] Displaying of deeplink in long headings destroys flow of text

### ISSUE THREAD

**Issue by fliptrail** [RocketChat/docs-old#1219]
When the user hovers over the headings, a link icon is displayed. 
Due to it's position and CSS styling, it destroys the flow of text.

*Without mouse hover*
![Screenshot from 2019-04-09 15-46-19](https://user-images.githubusercontent.com/40834245/55792824-1a7b3600-5adf-11e9-9678-13769f547244.png)

*With mouse hover*
![Screenshot from 2019-04-09 15-47-16](https://user-images.githubusercontent.com/40834245/55792895-38e13180-5adf-11e9-9896-ab3eb0a69333.jpg)

This looks odd and distracting to the user.

**Comment by Rodriq** [comment]
That heading is been rendered by markdown and has no custom styling on it.

**Comment by sudhansu3299** [comment]
Can I take up this bug? @MartinSchoeler
