### ISSUE TITLE
Query is not working

### ISSUE THREAD

**Issue by rh58** [RocketChat/docs-old#1224]
Help please.
I have some data like this(when I use api/v1/groups.messages?roomName=testreport):
```
{
"messages": [
  {
"_id": "yfDwaPCygQPcGahib",
"rid": "P8rwbTo63eJrLBu4q",
"msg": "4/2 LALALLALALALALALA",
"ts": "2019-04-10T09:25:06.003Z",
"u": {
"_id": "4SthPEcWNo2hXgGy8",
"username": "rh58",
"name": "Raymond.P.Huang (tw mis.twtc01.Newegg) 61542"
},
"_updatedAt": "2019-04-10T09:25:06.007Z",
"editedBy": null,
"editedAt": null,
"emoji": null,
"avatar": null,
"alias": null,
"customFields": null,
"attachments": null,
"mentions": [],
"channels": [],
}],
"count": 6,
"offset": 0,
"total": 6,
"success": true
}
```
When I use query in API URL, like the doc shows, I get no element in the message array:
`https://localhost:3000/api/v1/groups.messages?roomName=testreport&query={"_updatedAt":{"$eq":{"$date":"2019-04-10T00:43:11.768Z"}}} (GET)`

**Comment by d-gubert** [comment]
It seems like your query is considering **even the milliseconds** of the date that you want to filter, which wouldn't match any record that weren't updated **at the very same millisecond** as your parameter.

Usually, when querying dates, it's common to use a range of dates to filter, like the beginning and end of a day, for instance. Could you try using the `$gte` and `$lt` operators in your query and verify if it still doesn't work?

**Comment by rh58** [comment]
> It seems like your query is considering **even the milliseconds** of the date that you want to filter, which wouldn't match any record that weren't updated **at the very same millisecond** as your parameter.
> 
> Usually, when querying dates, it's common to use a range of dates to filter, like the beginning and end of a day, for instance. Could you try using the `$gte` and `$lt` operators in your query and verify if it still doesn't work?

Thank you.
But it's not working.
Actually, I have tried $gt, $gte, $lt, ...etc, and they are not working.
And the other query in another field is not working too:
`https://localhost:3000/api/v1/groups.messages?roomName=testreport&query={"username":{"$regex":"rh58"}}`

**Comment by MartinSchoeler** [comment]
Hey, looks like you are looking for support.You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
