### ISSUE TITLE
Improving the docker-compose steps documentation

### ISSUE THREAD

**Issue by franckadil** [RocketChat/docs-old#1231]
Hello,

How can I submit a simple documentation steps beginners friendly for a stack running rocket-chat-nginx-and letsencrypt-chatbot out of the box without struggle ?

Thanks in advance.

**Comment by reetp** [comment]
If there is an existing document you want to edit and add to you can do that  easily enough

If not then the best thing to do is.... read the documentation

https://github.com/RocketChat/docs

https://github.com/RocketChat/docs/tree/master/contributing/documentation

You can of course post your guide here and people can review it for you.

**Comment by Rodriq** [comment]
The Rocket.Chat deployment with docker-compose documentation has been updated and improved including guides on the use of env variables. Please see here https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose
You can see guides on developing and deploying bots here https://developer.rocket.chat/bots/creating-your-own-bot-from-scratch
