### ISSUE TITLE
Documentation to update to 1.0 is broken

### ISSUE THREAD

**Issue by memorais** [RocketChat/docs-old#1288]
At the official page documentation the link to update to version 1.0 [1] is broken returning 404.

[1] - https://rocket.chat/docs/installation/updating/updating-to-1-0/

**Comment by Joonhkt** [comment]
The link is https://rocket.chat/docs/installation/updating/to-1-0/

**Comment by memorais** [comment]
Ok, thanks it but should be fixed on the official page documentation.

**Comment by Rodriq** [comment]
I'll try to fix adjust that.

**Comment by MartinSchoeler** [comment]
Fixed in https://github.com/RocketChat/docs/commit/b53eac0c76813783498c73bd91ffcb6184b818be
