### ISSUE TITLE
In Docker Configure a replica set for MongoDB

### ISSUE THREAD

**Issue by KiritakeKumi** [RocketChat/docs-old#1293]
https://rocket.chat/docs/installation/manual-installation/mongo-replicas/

Excuse me, how to configure in Docker??

In addition, can you start Rocket without configuring the replica set?

**Comment by sshniro** [comment]
This documentation explains how to create a replica set using docker.

https://github.com/RocketChat/docs/tree/master/installation/docker-containers/high-availability-install

**Comment by sshniro** [comment]
You can refer this on how to configure a replica set.
https://github.com/RocketChat/Docker.Official.Image/pull/82/files

And Rocket chat has breaking change after version 1.0. 
https://github.com/RocketChat/Rocket.Chat/pull/14227

**Comment by Rodriq** [comment]
Deploying with docker-compose, replica set is specified by setting the `MONGO_OPLOG_URL` variable see docs https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose
Creating and configuring replica set is explained here https://github.com/RocketChat/Rocket.Chat/pull/14227
