### ISSUE TITLE
Warn about iframe features policy required on iframe integration

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/docs-old#1340]
For instance, to allow geolocation, camera, and microphone on iframe an `allow` attribute must be added:

```html
<iframe src="https://open.rocket.chat/" allow="geolocation; microphone; camera"></iframe>
```

**Comment by Rodriq** [comment]
That has been added here https://docs.rocket.chat/guides/administration/admin-panel/settings/general#iframe-integration
