### ISSUE TITLE
sending postMessage does not work

### ISSUE THREAD

**Issue by whytspace** [RocketChat/docs-old#1360]
Hi guys,

I tried to implement rocket.chat using an iFrame, which worked just fine. But I'm struggling with automatically authorizing the users with a token. I have a small backend service that calls the rocket.chat API (https://open.rocket.chat/api/v1/login) and returns the token. Now I want to send this token to the iFrame via postMessage, as [described in the docs](https://rocket.chat/docs/developer-guides/iframe-integration/commands/)

Strange thing is, even though I did "Enable Send" and "Enable Receive" in Admin > General > Iframe integration, **rocket.chat does not respond to any of my commands**. I tried it both, my local rocket.chat instance (running on `localhost:3010`) and the `open.rocket.chat` server.

Here is the code (actually inside my react app, but that's not relevant here):
```html
<iframe src="https://open.rocket.chat/" id="rocketchat"></iframe>
```
Trying to run this from console:
```js
document.getElementById('rocketchat').contentWindow.postMessage({
  externalCommand: 'go',
  path: '/channel/general'
}, '*')
```
or the login command:
```js
document.getElementById('rocketchat').contentWindow.postMessage({
  externalCommand: 'login-with-token',
  token: 'my-token-from-rocket-chat-api'
}, '*')
```

Also, when I [add an event listener for outgoing events](https://rocket.chat/docs/developer-guides/iframe-integration/events/), I can see that all messages I send in are being sent back out. I can also see all the other messages, such as "room-opened".

Am I doing something wrong? Did I miss one of the settings?

Rocket.Chat version: 1.2.1 (via docker)
It is a new instance with a clean database. Only settings I changed are "Enable Send" and "Enable Receive" in "Admin > General > Iframe integration"

Thanks,
David

**Comment by whytspace** [comment]
Sorry for opening this issue here. I guess the https://github.com/RocketChat/Rocket.Chat/ repository would have been a more appropriate location. [Reposted there](https://github.com/RocketChat/Rocket.Chat/issues/14987).

You may close this issue.

**Comment by reetp** [comment]
> You may close this issue.

I think you can close it yourself as you opened it?

**Comment by whytspace** [comment]
Didn't notice that. :)
