### ISSUE TITLE
[REST API] Missing closing curly bracket

### ISSUE THREAD

**Issue by a5his** [RocketChat/docs-old#138]
User update API example has a missing curly bracket. 

Do look at the attached screenshot. 

<img width="669" alt="screen shot 2016-12-07 at 9 21 32 am" src="https://cloud.githubusercontent.com/assets/330362/20953885/ae5b25f0-bc5e-11e6-9ecb-640564dab9b0.png">

**Comment by graywolf336** [comment]
Closed via #139
