### ISSUE TITLE
problem running the docs on Docker

### ISSUE THREAD

**Issue by edenhermelin** [RocketChat/docs-old#1382]
I tried to containerize the documentation project and to run it 0in a docker container and got the following error:

>  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
>                     Invalid US-ASCII character "\xE2" on line 5
> jekyll 3.7.4 | Error:  Invalid US-ASCII character "\xE2" on line 5

I looked it up online and made changes from people's similar issues (such as exporting the locale to utf8, adding `@charset "utf-8";` to the scss files, etc.

Im using the following Dockerfile:

> FROM ruby:latest
> 
> WORKDIR /rocketchat-website
> 
> COPY . .
> 
> RUN bundle install
> 
> EXPOSE 4000
> 
> CMD ["bundle", "exec", "jekyll serve --incremental --safe"]
> 

I'm not so familiar with Ruby, maybe it's an env problem that someone had while serving the docs in the common way?

**Comment by edergillian** [comment]
You need to add these lines to your Dockerfile:

```
ENV LC_ALL=C.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
```
It should work after this.
