### ISSUE TITLE
Keyboard shortcuts are undocumented

### ISSUE THREAD

**Issue by aspiers** [RocketChat/docs-old#1387]
I went to https://rocket.chat/docs/ and searched for "keyboard", "shortcuts", and "hotkeys".  None of these revealed any documentation for keyboard shortcuts.  After some searching I finally found https://github.com/RocketChat/Rocket.Chat/issues/46 but that just provides a `/help` slash command within the web client.  IMHO keyboard shortcuts should be documented in the user guide as well.

**Comment by amottier** [comment]
I found a little bit of what I guess is legacy documentation from a fork of https://github.com/RocketChat/docs available at: https://github.com/zenorocha/Rocket.Chat.Docs/tree/master/4.%20User%20Guides/Keyboard-Shortcuts

I didn't find any documentation related to shortcut on https://github.com/RocketChat/docs.

**Comment by ulope** [comment]
This is a big problem for onboarding users for us.
We had some people that were very unhappy with RC because they didn't know about the shortcuts and had no way of finding out.

**Comment by Faria1212** [comment]
Please find the doc here. https://docs.rocket.chat/guides/user-guides/keyboard-shortcuts

**Comment by pho3nixx** [comment]
Would it make sense to add formatting shortcuts like bold (`ctrl` + `b`) and italic (`ctrl` + `i`) there, too or are they being considered "general knowledge" in the meantime? Maybe there exist more, but I personally only know and use these frequently for formatting.
Hint: there's a typo with missing `o` at `Cntrol` right now (last line).

**Comment by Faria1212** [comment]
Yes. We believe that is common knowledge. Thank you for pointing out the typo

**Comment by novoid** [comment]
> Yes. We believe that is common knowledge.

Well, I'd prefer to have that added to the documentation.

Yes, if there is a feature to make something bold, it usually is ctrl+b. However, it is not that obvious to everybody that there is the possibility to format a string that way in Rocket.Chat. The discoverability is not given. Therefore, a complete list of shortcuts would be a benefit for the common user in my perspective.

For the sake of completeness, I'd also add ctrl+c ctrl+v ctrl-x - it doesn't hurt. Studies show that many users assume that there is no clipboard when there is no button or menu entry for it. (_Lane2005 - Hidden costs of graphical user interfaces: Failure to make the transition from menus and icon toolbars to keyboard shortcuts_)

**Comment by Faria1212** [comment]
We have added them. Thanks
