### ISSUE TITLE
docker-compose.yml error

### ISSUE THREAD

**Issue by danieasv** [RocketChat/docs-old#1390]
When I follow the guide for [deploying Rocket Chat on AWS](https://rocket.chat/docs/installation/paas-deployments/aws/), create the docker-compose.yml and reboot, I get this error: `Unsupported config option for services service: 'rocketchat'`

Could this be a syntax error?

**Comment by cyrilselasi** [comment]
the docker-compose version specified doesn't support version 2. Use a newer version of docker-compose to resolve this. 
`sudo -i curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose chmod +x /usr/local/bin/docker-compose exit`

**Comment by danieasv** [comment]
Thanks a lot, it works now.
