### ISSUE TITLE
[BUG] Right toc breaks on bigger screens

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/docs-old#1391]
![image](https://user-images.githubusercontent.com/20868078/63267048-a2c8cf00-c267-11e9-93fc-1c6402614b52.png)

**Comment by bandantonio** [comment]
The same bug appears when working with docs locally

**Comment by Rodriq** [comment]
Will try to check this out.

**Comment by bandantonio** [comment]
@MartinSchoeler I think the bug is not relevant anymore after the switch to GitBook

**Comment by MartinSchoeler** [comment]
Closing this as it is not relevant anymore
