### ISSUE TITLE
build-essential is not available and python-minimal is not available

### ISSUE THREAD

**Issue by longtqdayma** [RocketChat/docs-old#1397]
longdv@longdv-VirtualBox:~$ sudo apt install g++ build-essential git curl python-minimal
[sudo] password for longdv: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package build-essential is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python-minimal is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'build-essential' has no installation candidate
E: Package 'python-minimal' has no installation candidate
longdv@longdv-VirtualBox:~$

**Comment by MartinSchoeler** [comment]
This issue is not related to Rocket.Chat docs.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).
If you think we are closing this in error, please reopen this with updated details.
Thanks!
