### ISSUE TITLE
Email configuration missing parameters

### ISSUE THREAD

**Issue by juliensl** [RocketChat/docs-old#1407]
Hi ! 

We do not have any information about the pool and ignoreTLS parameter for the SMTP configuration.
An other issue was open, #1108 , but I do not know why it was closed without the fix.

[/administrator-guides/email/setup/README.md](https://github.com/RocketChat/docs/blob/master/administrator-guides/email/setup/README.md)

Thank you !

Julien.

**Comment by Faria1212** [comment]
https://docs.rocket.chat/guides/administration/admin-panel/settings/email/setup
