### ISSUE TITLE
Heroku One Click Error: Unable to find Mongodb Oplog.

### ISSUE THREAD

**Issue by tjrules** [RocketChat/docs-old#1412]
Just finished troubleshooting Heroku One-click build. There were no instructions for setting up oplog tailing When the user attempts a one-click build.  Here are the steps that I used to fix the problem.

1. The user needs to upgrade to a paid mlab plan, [instructions](https://devcenter.heroku.com/articles/mongolab#changing-plans) 

2. Then setup an oplog user in mlab [instructions](https://docs.mlab.com/oplog/)

3. Finally, in Heroku, go to your user dashboard, select the dyno you're working in, click on settings, click reveal config vars, then in the empty space for the KEY input type in MONGO_OPLOG_URL . The VALUE input should look something like this:

mongodb://<dbuser>:<dbpassword>@ds012345-a0.mlab.com:56789,ds012345-a1.mlab.com:56790/local?replicaSet=rs-ds012345&authSource=admin

Hope this helps

**Comment by jekuno** [comment]
Merging #1438 fixes this issue.

**Comment by Rodriq** [comment]
Heroku is no longer a supported deployment method.
A detailed explanation as to why see #1855 

Here is a [list of cloud deployments](https://docs.rocket.chat/quick-start/installing-and-updating/paas-deployments) you can look into
