### ISSUE TITLE
S3 Frankfurt Region

### ISSUE THREAD

**Issue by jsenon** [RocketChat/docs-old#145]
When I tried to download image, uploaded in S3 Frankfurt region I receive error 👍 
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256

Does Rocket.chat will support v4 for authentication?
http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4

**Comment by graywolf336** [comment]
@jsenon This is probably best asked on the main repository as it seems like a bug. Thoughts @sampaiodiego?

**Comment by jsenon** [comment]
Indeed. Sorry
