### ISSUE TITLE
Update channel name via REST

### ISSUE THREAD

**Issue by mahmoudmahdi24** [RocketChat/docs-old#146]
Hello,

How can i edit a channel parameters ( name for example ) using the REST API ? 
I have only found how to create a channel in the documentation.

Thanks,

**Comment by graywolf336** [comment]
Currently not possible until https://github.com/RocketChat/Rocket.Chat/pull/5140 and https://github.com/RocketChat/Rocket.Chat.Docs/pull/142 are merged.

**Comment by mahmoudmahdi24** [comment]
When are you planning approximately to make that merge ? 
Thanks,

**Comment by graywolf336** [comment]
It should be merged either today or start of next week. :)

**Comment by mahmoudmahdi24** [comment]
Great ! Let me know when it's done
Thanks

**Comment by graywolf336** [comment]
@mahmoudmahdi24 It has been merged into the develop branch already.
