### ISSUE TITLE
Bamboo integration plugin missing

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/docs-old#1474]
I've followed tips in the article:
https://rocket.chat/docs/administrator-guides/rocket-chat-apps/bamboo-integration/

But it seems that there is no "bamboo integration" plugin in the Marketplace. Why? Is it any way to connect RocketChat to the Bamboo?

**Comment by Rodriq** [comment]
The docs on bamboo integration is now here https://docs.rocket.chat/guides/app-guides/atlassian/bamboo-integration

The bamboo integration comes for free when your workspace is registered with an [enterprise license](https://docs.rocket.chat/guides/enterprise-edition-trial) 

![image](https://user-images.githubusercontent.com/39289592/177182915-4cf6947d-a647-4be3-8557-8101df419426.png)
