### ISSUE TITLE
Incoming webhook payload structure is not properly documented

### ISSUE THREAD

**Issue by ulope** [RocketChat/docs-old#1477]
There is no place where the exact supported structure of incoming webhook payloads is documented. 

There are bits and pieces in various places and links to the slack documentation which has somewhat drifted feature wise from what RC supports.

It would be very useful to have complete overview of all fields / features supported by incoming webhooks in one place.

**Comment by ChristySujitha** [comment]
Updated Incoming webhook doc: https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/integration-endpoints/create
