### ISSUE TITLE
Update of documentation - Apache SSL proxy configuration for subfolder installation

### ISSUE THREAD

**Issue by Abraka** [RocketChat/docs-old#151]
## Apache SSL proxy configuration for subfolder installation
ProxyPreserveHost On                                                                                                                                                    
ProxyPassMatch ^/sockjs/(.*)/websocket ws://10.10.10.1:3000/chat/sockjs/$1/websocket                                                                                   
ProxyPass                /chat/    http://10.10.10.1:3000/chat/                                                                                                                  
ProxyPassReverse   /chat/    http://10.10.10.1:3000/chat/

**Comment by Abraka** [comment]
I forgot to mention that when using subfolder, there is problem with logo, because footer for logo have hard link to https://your.domain.com/assets/logo.png - "chat" subfolder missing in link.

**Comment by MartinSchoeler** [comment]
This issue is old and lack of details. I will be closing this. If this is still relevant, please open a new issue with more details. Thanks!
