### ISSUE TITLE
Misaligned item is not misaligned (Markdown Style Guide)

### ISSUE THREAD

**Issue by BaerMitUmlaut** [RocketChat/docs-old#1516]
See: https://rocket.chat/docs/contributing/documentation/markdown-styleguide/#md005---no-inconsistent-indentation-for-list-items-at-the-same-level

```
- Item 1
    - Nested Item 1
    - Nested Item 2
    - A misaligned item
```
should be
```
- Item 1
    - Nested Item 1
    - Nested Item 2
   - A misaligned item
```

**Comment by faezegarshasbi** [comment]
hello
it doesnt work in rocket, I mean ,when i type it my out put is simple text  unordered and withou any format
can u help me?
