### ISSUE TITLE
rocketchat mongodb the unit files have no [Install] section systemctl

### ISSUE THREAD

**Issue by zorenlegaspi-bpa** [RocketChat/docs-old#1535]
Hello guys,

I keep on getting this error when I try to execute this command:
Command: 
sudo systemctl enable rocketchat_mongo

Error:

> The unit files have no [Install] section. They are not meant to be enabled using systemctl.
> Possible reasons for having this kind of units are:
> 1) A unit may be statically enabled by being symlinked from another unit's
>    .wants/ or .requires/ directory.
> 2) A unit's purpose may be to act as a helper for some other unit which has
>    a requirement dependency on it.
> 3) A unit may be started when needed via activation (socket, path, timer,
>    D-Bus, udev, scripted systemctl call, ...).

I followed all the instructions given in [this article](https://rocket.chat/docs/installation/paas-deployments/aws/). (Already triple-checked but still no luck).

Can anyone please help me out?

Thanks!

**Comment by lucasduete** [comment]
Hi, see PRs #1559 and #1560 to workarounds in AWS installation guide

**Comment by Rodriq** [comment]
AWS guide details using specified versions of Docker Compose and Mongo Images https://docs.rocket.chat/quick-start/installing-and-updating/paas-deployments/aws#install-docker-and-docker-compose
In the compose file, you can see the version of mongo used
As also mentioned here https://github.com/RocketChat/docs/pull/1560
