### ISSUE TITLE
Telegram incoming WebHook script error

### ISSUE THREAD

**Issue by zulzorrander** [RocketChat/docs-old#1546]
I've encountered an issue with telegram integration Webhook. Messages that a written in telegram chat are not being forwarded to the appropriate chat in Rocket.

Telegram API through `/getWebhookInfo` reports the following 
`{"ok":true,"result":{"url":"<my_rocketchat_url>/hooks/<my_token>","has_custom_certificate":false,"pending_update_count":0,"last_error_date":1576680084,"last_error_message":"Wrong response from the webhook: 400 Bad Request","max_connections":40}}` 

RocketChat logs report the following
`{ icon_emoji: ':ghost:',
text: 'Example message',
attachments:
[ { title: 'Rocket.Chat',
title_link: 'https://rocket.chat',
text: 'Rocket.Chat, the best open source chat',
image_url: '/images/integration-attachment-example.png',
color: '#764FA5' } ] }
server.js:204 Integrations ➔ Incoming WebHook.error [Error running Script in Trigger adminsChatTelegram :]
var Script=function(){function Script(){}var _proto=Script.prototype;_proto.process_incoming_request=function process_incoming_request(_ref){var request=_ref.request;console.log(request.content);if("edited_message"in request.content){request.content.message=request.content.edited_message}var from=request.content.message.from;var who=from.username;var icon_url="/avatar/"+from.username+".jpg";if(!who){if(from.first_name&&from.last_name){who=from.first_name+" "+from.last_name}else if(from.first_name){who=from.first_name}else{who=from.last_name}icon_url="/avatar/"+request.content.message.from.first_name+".jpg"}var body=request.content.message.text;if(!body){if(request.content.message.hasOwnProperty("sticker")&&request.content.message.sticker.emoji){body=request.content.message.sticker.emoji}else{return{}}}return{content:{username:who,icon_url:icon_url,text:body}}};return Script}();
server.js:204 Integrations ➔ Incoming WebHook.error [Stack:]
server.js:204 Integrations ➔ Incoming WebHook.error   Error: TypeError: Cannot read property 'from' of undefined
at Promise.catch (evalmachine.<anonymous>:11:33)
at /snap/rocketchat-server/1418/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40`

Integration has been set up following [this guide](https://github.com/RocketChat/docs/blob/master/administrator-guides/integrations/telegram/README.md) and has been working for about 4 months without any issues

RocketChat server is installed on Ubuntu16.04 VM from snap. The server itself is placed behind Nginx to utilize SSL connection
RocketChat server info:
Rocket.Chat
Version	2.3.1
Apps Engine Version	1.7.0
[...]
Running Instances	1
OpLog	Enabled

Commit
Hash	dde5b16dbe00cc4c5e88527e725773f78c0ced66
Date	Mon Dec 9 18:19:48 2019 -0300
Branch	HEAD
Tag	2.3.1
Author	Diego Sampaio
Subject	Merge pull request #15941 from RocketChat/release-2.3.1
Runtime Environment
OS Type	Linux
OS Platform	linux
OS Arch	x64
OS Release	4.15.0-70-generic
Node Version	v8.15.1
Mongo Version	3.6.14
Mongo Storage Engine	wiredTiger
OS Uptime	32 days, 18 hours, 35 minutes, 7 seconds
OS Load Average	0.23, 0.19, 0.18
OS Total Memory	7.72 GB
OS Free Memory	3.70 GB
OS CPU Count	8

Build Environment
OS Platform	linux
OS Arch	x64
OS Release	4.15.0-1052-aws
Node Version	v8.15.1

Nginx info
nginx version: nginx/1.10.3 (Ubuntu)
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-stream --with-stream_ssl_module --with-mail --with-mail_ssl_module --with-threads

Any ideas on what may cause the error and the possible ways to fix this?

**Comment by dudanogueira** [comment]
Hi!

We have release a Telegram App that can now integrate Telegram and Rocket.Chat's Omnichannel.

Please, refer this doc for more information:
https://docs.rocket.chat/guides/app-guides/omnichannel-apps/telegram-app

I will mark [the old doc for review,](https://docs.rocket.chat/guides/administration/admin-panel/integrations/telegram) as telegram payloads probable has changed and may not work right now.

**Comment by Rodriq** [comment]
- Please make sure your `URL` is publicly available. The guide is here https://docs.rocket.chat/guides/administration/admin-panel/integrations/telegram
- Enable the **webhook** and **script** on the configuration page.
When you test the webhook: `https://api.telegram.org/bot[myauthorization-token]/setwebhook?url=[Incoming_Webhook_Link_from_Rocket.Chat]`
You should get a success
``` json
{
"ok": true,
"result": true,
"description": "Webhook was set"
}
```
