### ISSUE TITLE
Heroku One Click Deployment Stuck

### ISSUE THREAD

**Issue by jekuno** [RocketChat/docs-old#1552]
Installation of RocketChat on Heroku hangs.

# Reproduce
Run the Heroku one click deployment as described at
* https://github.com/RocketChat/Rocket.Chat/blob/master/README.md#heroku and
* https://github.com/RocketChat/docs/blob/master/installation/paas-deployments/heroku/README.md

by clicking the one click deploy button https://heroku.com/deploy?template=https://github.com/RocketChat/Rocket.Chat/tree/master.

The setup then stops at the following point:
```
-----> Building Meteor app with ROOT_URL: https://xxxxxx.herokuapp.com
Livechat: updating npm dependencies -- uglify-js...

WARNING: npm peer requirements (for juliancwirko:postcss) not installed:
 - postcss@7.0.6 installed, postcss@^6.0.22 needed
 - postcss-load-config@2.0.0 installed, postcss-load-config@^1.2.0 needed

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies
```

**Comment by Rodriq** [comment]
Rocket.Chat no longer support Heroku one-click deployment at the moment. You can check the various PASS deployments here https://docs.rocket.chat/quick-start/installing-and-updating/paas-deployments 
OR 
See other deployments here https://docs.rocket.chat/quick-start/installing-and-updating/other-deployment-methods
