### ISSUE TITLE
Installing React Native mobile apps

### ISSUE THREAD

**Issue by ugintl** [RocketChat/docs-old#1558]
First I installed mattermost, but the free version has restrictions. So I installed rocket chat. I have successfully installed rocket chat server with ssl on Ubuntu 18 on AWS hosting. Now I want to build and configure mobile clients for my own server. I am interested in React Native apps. Please share a detailed step by step guide.

I am a beginner level, but I can follow the instructions. So far I have just found this, but I am not sure if it is all steps what I need to build the app. I am on windows 10.

 1. https://github.com/RocketChat/Rocket.Chat.ReactNative#installing-dependencies and 2. https://github.com/RocketChat/Rocket.Chat.ReactNative#how-to-run

**Comment by Rodriq** [comment]
Guides on Rocket.Chat mobile apps can be found in the developers docs here https://developer.rocket.chat/mobile-app/
