### ISSUE TITLE
Incomplete information for Okta integration

### ISSUE THREAD

**Issue by amitpandey-intelligentb** [RocketChat/docs-old#1566]
https://github.com/RocketChat/docs/tree/master/administrator-guides/authentication/oauth/okta

There is no mention of adding an oauth app under Administration->Oauth Apps. Instead the doc stops at configuring oauth and states that login would work, which in my case doesn't and it needs improvement/update.

**Comment by syedmuhammadkumail** [comment]
i am having the same problem. I am unable to integrate rocket chat with okta even after following the full documentation.

**Comment by Rodriq** [comment]
You can check [here](https://developer.okta.com/docs/guides/sign-into-web-app/nodeexpress/main/#create-an-okta-app-integration) on how to get the OAuth id and secret

We have the docs here https://docs.rocket.chat/guides/administration/settings/oauth/other-oauth-setup#okta-oauth
