### ISSUE TITLE
AWS EKS Helmchat is unable to dowload image from private repo. 

### ISSUE THREAD

**Issue by vijaay3d** [RocketChat/docs-old#1568]
https://github.com/RocketChat/docs/blob/master/installation/paas-deployments/aws/eks/README.md

Below command with repository refrence, pod rc-rocketchar go into InvalidImageName state. 

helm install --name=rc \
--set mongodb.mongodbUsername=rocketchat \
--set mongodb.mongodbPassword=superSecure \
--set mongodb.mongodbDatabase=rocketchat \
--set mongodb.mongodbRootPassword=superSecureToo \
--set image.repository=217273820646.dkr.ecr.us-east-1.amazonaws.com/046e16ad-a193-4c5b-9f1f-d2619d9c5cd6/cg-1684305143/rocket.chat \
--set image.tag=0.71.1-latest \
--set ingress.enabled=true \
--set host=your-hostname.your-domain.com \
--set ingress.annotations."kubernetes\.io/ingress\.class"=traefik \
stable/rocketchat

error 

45s         Warning   InspectFailed            pod/rc-rocketchat-f5f5f6698-vtkp6                           Failed to apply default image tag "map[tag:0.71.1-latest repository:217273820646.dkr.ecr.us-east-1.amazonaws.com/c87d63fd-e44d-4368-82e0-24bd42b21a84/cg-2246218297/rocket.chat]": couldn't parse image reference "map[tag:0.71.1-latest repository:217273820646.dkr.ecr.us-east-1.amazonaws.com/c87d63fd-e44d-4368-82e0-24bd42b21a84/cg-2246218297/rocket.chat]": invalid reference format

**Comment by Rodriq** [comment]
Here you can find guide on how to install with docker https://docs.rocket.chat/quick-start/installing-and-updating/paas-deployments/aws
