### ISSUE TITLE
Add pagerduty integration

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/docs-old#157]
https://github.com/kajisaap/rocketchat-pagerduty

**Comment by antgel** [comment]
What's the point of this ticket? To bring PD integration inside RC i.e. without needing a webhook?

**Comment by antgel** [comment]
Oops, I just saw it's in the .Docs repo. Sorry for the noise.

**Comment by docsncode** [comment]
@MartinSchoeler please add the pagerduty integration to the documentation's list of integrations.

**Comment by MartinSchoeler** [comment]
Moved to #661
