### ISSUE TITLE
Github Empty Incoming WebHook Scripting

### ISSUE THREAD

**Issue by decryp2kanon** [RocketChat/docs-old#1599]
https://github.com/RocketChat/docs/blob/master/administrator-guides/integrations/README.md

i followed this tutorial, but it posts empty post.

whats went wrong?

![image](https://user-images.githubusercontent.com/60179867/74081119-bcb4d300-4a8e-11ea-9cfc-5dc58f96e75f.png)

![image](https://user-images.githubusercontent.com/60179867/74081137-ecfc7180-4a8e-11ea-9ea1-aed36fee8c9b.png)

**Comment by elMor3no** [comment]
Same error here;

**Comment by decryp2kanon** [comment]
i gave up :joy:

**Comment by dudanogueira** [comment]
Hi!

We will review this doc soon. Can you say you still face this Issue?

Related doc: https://docs.rocket.chat/guides/administration/admin-panel/integrations/github

**Comment by elMor3no** [comment]
Yes... RocketChat don't integrate with Github... the doc is wrong

**Comment by Rodriq** [comment]
Updated docs https://docs.rocket.chat/guides/administration/admin-panel/integrations/github
