### ISSUE TITLE
rocketchat_server.can not upload files,imgs,voices,and all files

### ISSUE THREAD

**Issue by 57594261** [RocketChat/docs-old#1603]
rocketchat_server.can not upload files,imgs,voices,and all files
![image](https://user-images.githubusercontent.com/48671397/74098180-09acae00-4b50-11ea-9c58-87cff51adc67.png)
when i upload files . at 0%...

**Comment by ValerioCietto** [comment]
Try the web client and look at the browser console.
If you are admin, look at server logs.

It could be a permission problem, no space on disk or network error.
