### ISSUE TITLE
Gitlab Self-hosted and Rocket.Chat self-hosted integration issue

### ISSUE THREAD

**Issue by dhawaljaiswal** [RocketChat/docs-old#1641]
Followed official documentation but getting error while testing web hooks. https://rocket.chat/docs/administrator-guides/integrations/gitlab/

Cannot read property 'replace' of undefined.

Note: I fixed double slash I found in GitLab App Detail page under POST Webhook 
curl -X POST http://chat.ratufatech.com:3000//api/apps/public/6842d-1461-4983-9ea7-fde74b15026c/webhook 
In above url I fixed it to curl -X POST http://chat.ratufatech.com:3000/api/apps/public/6842d-1461-4983-9ea7-fde74b15026c/webhook

I used http://chat.ratufatech.com:3000/api/apps/public/6842d-1461-4983-9ea7-fde74b15026c/webhook as url 

After this I was getting error that room doesn't exists, then I created one, it was like root-projectname

however now it give error like Cannot read property 'replace' of undefined. This is probably script I copied from office documentation is written considering I am using gitlab.com , but I am using self hosted GitLab CE.

Please help. Thank you.

**Comment by Rodriq** [comment]
Please check the updated instructions on how to configure here https://docs.rocket.chat/guides/administration/admin-panel/integrations/gitlab
