### ISSUE TITLE
Installation on Debian 10 »Buster«

### ISSUE THREAD

**Issue by ITfee** [RocketChat/docs-old#1650]
Unfortunately the documentation here https://rocket.chat/docs/installation/manual-installation/debian/ has no hint on Debian 10 aka Buster.
To read external repositories a public GPG-key is needed.
In the current documentation there is only a description on how to install with the old Debian version.
Without a current key the repository can't be read and therefore the packages can't be installed.

**Comment by Rodriq** [comment]
Signing with key is required when installing dependencies like MongoDB, nodejs etc and that can be done with the flag `| sudo apt-key add -` Which is specified on the dependencies' original deployment page.

The docs have been updated https://docs.rocket.chat/quick-start/deploying-rocket.chat/other-deployment-methods/manual-installation/debian-based-distros/debian
