### ISSUE TITLE
Password replaced for existing user

### ISSUE THREAD

**Issue by slowflyer** [RocketChat/docs-old#1651]
If you use REST API `/api/v1/users.create`
to create a new user account and the username already exists, you receive an error message telling, that the user already exists, but the password of the existing user is replaced by the password you send with the new account credentials.

**Comment by Rodriq** [comment]
@slowflyer 
  I tested on my local server and it wasn't the case.
What version of Rocket.Chat are you running?

**Comment by slowflyer** [comment]
Hi,
I'm using 3.0.3, but no matter.
Sorry forgot to close this issue, found the bug in my code end of last week.
