### ISSUE TITLE
Possible YAML Error in docker-compose.yml

### ISSUE THREAD

**Issue by fanntom** [RocketChat/docs-old#1665]
While trying to run Rocket chat in an AWS t2.micro instance following the official guide:
[https://rocket.chat/docs/installation/paas-deployments/aws/]

I ran into an error while running docker-compose up -d
ERROR: yaml.scanner.ScannerError: while scanning a simple key
  in "./docker-compose.yml", line 33, column 5
could not find expected ':'
  in "./docker-compose.yml", line 37, column 16

The code I used is same with the code posted in the guide except for the domain name.

**Comment by PauloEmmerich** [comment]
Same error here. Trying to find out how to initialize replicas. Was able to "compose up" removing  mongo-init-replica: from yml

**Comment by PauloEmmerich** [comment]
it works using:

    mongo-init-replica:
        image: mongo:4.0
        command: 'bash -c "for i in `seq 1 30`; do mongo mongo/rocketchat --eval \"rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})\" && s=$$? && break || s=$$?; echo \"Tried $$i times. Waiting 5 secs...\"; sleep 5;  done; (exit $$s)"'
        depends_on:
        - mongo

**Comment by lithiumlab** [comment]
@PauloEmmerich excellent hint!

**Comment by Rodriq** [comment]
This is all good now and the updated docs can be located here https://docs.rocket.chat/quick-start/installing-and-updating/paas-deployments/aws
