### ISSUE TITLE
Installation manual for Docker has TODO left - Updating & backing up

### ISSUE THREAD

**Issue by luixxiul** [RocketChat/docs-old#1681]
`https://rocket.chat/install` links [this page](https://rocket.chat/docs/installation/docker-containers) as the installation manual for Docker.

I noticed that there was a TODO still left to `Add section for updating & backing up`.

https://rocket.chat/docs/installation/docker-containers/#11-todo

**Comment by Rodriq** [comment]
Docker Installs update docs is here => https://docs.rocket.chat/quick-start/upgrading-rocket.chat#upgrading-rocket.chat-on-docker
Backup/Restore of Mongo is here => https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose/docker-containers/docker-mongo-backup-and-restore
