### ISSUE TITLE
Update documents to instruct to remove or comment out the init section of docker-compose

### ISSUE THREAD

**Issue by airdogvan** [RocketChat/docs-old#1682]
I did a pull of rocketchat which went well then I did a docker-compose up -d and the database got re-initialized because the init section had not been commented out.
Maybe make it very clear that the init section should be commented out after the first run of docker-compose.

**Comment by Rodriq** [comment]
Recent docs got it covered, https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose
Thanks
