### ISSUE TITLE
API v1: groups management

### ISSUE THREAD

**Issue by Cooker-Monster** [RocketChat/docs-old#170]
Hi !
Private Channels are not listed with "/api/v1/channels.list" even if the user belong to considered channel.
I'm still a little bit confused with Group as I thought that this noun was supposed to be replace by Channel (public/private).
Maybe I'm wrong ... or this is a work in progress and I must be patient or help !

**Comment by graywolf336** [comment]
You are correct groups are not listed under `/api/v1/channels.list` but **instead** are under `/api/v1/groups.list`.

**Comment by Cooker-Monster** [comment]
OK, so "Private Channel" means "Group", right ?

**Comment by engelgabriel** [comment]
Yes
