### ISSUE TITLE
im.create doesn't work for multiple usernames

### ISSUE THREAD

**Issue by AndrewLewis83** [RocketChat/docs-old#1702]
While using the REST API api/v1/im.create, I am able to create an instant message between two usernames as documented. The following parameter gets a successful return:

["username": "username1"]

However, when using im.create for three or more users, I get the following error:

`response is:SUCCESS: {
    error = "Body param \"roomId\" or \"username\" is required [error-room-param-not-provided]";
    errorType = "error-room-param-not-provided";
    success = 0;
}`

I sent the following as a parameter using the iOS library Alamofire, just as the one shown above:

["usernames": ["username1", "username2"]]

My input seems to follow the documentation. Is this a bug, or am I doing it wrong?

**Comment by Fishbowler** [comment]
Is it possible that your Rocket.Chat server is out of date?
Multi-user DMs is a relatively recent feature, introduced in v3.1 I think.
