### ISSUE TITLE
Broken link in RocketChat/docs/blob/master/administrator-guides/account-settings/README.md

### ISSUE THREAD

**Issue by gulfie** [RocketChat/docs-old#1710]
Broken link in RocketChat/docs/blob/master/administrator-guides/account-settings/README.md

The line : Use Default Blocked Domains List: Will block the email domains listed on this file
or
43 : - **Use Default Blocked Domains List**: Will block the email domains listed on this [file](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/lib/defaultBlockedDomainsList.js)

The given link shows up as a 403

**Comment by Faria1212** [comment]
https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/app/lib/server/lib/defaultBlockedDomainsList.js
The document has the current link now. Thank you
