### ISSUE TITLE
broken link in integration example

### ISSUE THREAD

**Issue by tb102122** [RocketChat/docs-old#1717]
https://github.com/RocketChat/docs/blob/master/administrator-guides/integrations/github/README.md

The link for the template in the following section is broken.

The Handlebars template used by Rocket.Chat to render messages from a JSON object may also be useful, and can be found **here.**

**Comment by engelgabriel** [comment]
I've removed the link since we are refactoring all Handlebars templates into ReacJS. We will add a section on the documentation about the templates once the refactoring is complete.
