### ISSUE TITLE
Internal Hubot documentation completely missing

### ISSUE THREAD

**Issue by ghost** [RocketChat/docs-old#172]
The documentation for the internal hubot is currently completely missing.

**Comment by Rohlik** [comment]
I think that we need wait for this https://github.com/RocketChat/Rocket.Chat/issues/6640
Big change coming....

**Comment by TomaszDom** [comment]
Is it maybe time to create documentation for it?

**Comment by apitt** [comment]
Hi all,

Does anybody know if it's possible to have Hubot listen for a file upload?  I'm trying to make a bot that can listen for a file upload and then respond with a message if the file extension is ".doc".  I haven't been able to figure out if file upload details are available to hubot.

**Comment by MartinSchoeler** [comment]
Moved to the Documentation Map https://github.com/RocketChat/docs/blob/master/contributing/documentation/missing-and-outdated-list/README.md#internal-hubot
