### ISSUE TITLE
HA documentation is confusing

### ISSUE THREAD

**Issue by mhow2** [RocketChat/docs-old#1720]
@frdmn and I found that the documentation at https://rocket.chat/docs/installation/docker-containers/high-availability-install/ is rather confusing or at least incomplete.

The setup at https://github.com/frdmn/docker-rocketchat works fine (with a single mongo instance).

I would also be in favor to provide more details for the mongo cluster if possible.

**Comment by engelgabriel** [comment]
We are working on a new guide: https://docs.rocket.chat/installation/micro-services-setup-beta

**Comment by Rodriq** [comment]
HA Documentation https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/docker-and-docker-compose/docker-containers/high-availability-install

Scaling and Microservices https://docs.rocket.chat/quick-start/scaling-rocket.chat
