### ISSUE TITLE
Gitbook merge prevents previous branches from merging/rebasing

### ISSUE THREAD

**Issue by Fishbowler** [RocketChat/docs-old#1724]
The simultaneous move & edit of lots of files has broken the ability to get WIP merged in.

I've mostly gotten history back into shape on a branch (https://github.com/surevine/Rocket.Chat-docs/commits/rewrite_docbook_merge) but it would need to be both force-pushed and fast-forwarded - a merge commit would introduce the same problem again.

Thoughts on viability?

**Comment by Sing-Li** [comment]
@engelgabriel  the gitbook problem with contributor's git history as mentioned.

**Comment by engelgabriel** [comment]
OK, but this is not a problem that should happen again, right? It is "just" a problem to be fixed once now.

**Comment by Fishbowler** [comment]
Absolutely. It only bothers the WIP and MRs outstanding prior to this commit. Unsure whether the effort required to fix this now (especially given the commits in since this was raised) is worth the effort saved in fixing up the proposed changes. You'd definitely know better than me. 

Was definitely an interesting problem to try to solve, even if it's not used here! Turns out that git gives up (by default) at not much over 100 moves in a single commit!
