### ISSUE TITLE
[Rest API] Login example with JSON 

### ISSUE THREAD

**Issue by a5his** [RocketChat/docs-old#173]
```
curl http://localhost:3000/api/v1/login \
     -d "user=myusername&password=mypassword"
```

```
curl -H "Content-type:application/json" \
      http://localhost:3000/api/v1/login \
      -d '{ "username": "myusername", "password": "mypassword" }'
```
I think the JSON call has typo. `username` should be `user`.

**Comment by graywolf336** [comment]
It can actually be either one, this was to demonstrate that.

**Comment by a5his** [comment]
@graywolf336 below is what i am seeing while using `username`.

<img width="309" alt="screen shot 2017-01-11 at 5 45 55 pm" src="https://cloud.githubusercontent.com/assets/330362/21847821/0dc705e4-d826-11e6-8831-c888123cc32f.png">

**Comment by graywolf336** [comment]
That's interesting as it has always worked for me, what version of
rocket.chat?

**Comment by a5his** [comment]
It is `0.48.2`. Now it is working on my local machine but not on a staging and its `https`. `user` works in staging. Strange!

**Comment by a5his** [comment]
@graywolf336 

Since browser authentication supports both username and email, I expected same support to API as well.

BTW, below is another way to log in.

```
curl -H "Content-type:application/json"  \   
      http://localhost:3000/api/v1/login \
      -d '{"user":"ashis@cloudfactory.com","password":"nepal"}'
```

`Response`

```
{
  "status": "success",
  "data": {
    "authToken": "-HYTyASph0kU6iz_ikKMEeMf3_eOXjaxmFqQeY2Nijz",
    "userId": "tTAibfAzxAhM4PnJ5"
  }
}
```

If you use `user` in a param then it supports both `username` and `email`. I think we should put this info in docs as well.
