### ISSUE TITLE
Documentation about how to upload files or images in livechat rooms

### ISSUE THREAD

**Issue by ValerioCietto** [RocketChat/docs-old#1741]
Hello, 
I'm trying to use the Livechat API to upload files in the livechat room created.

I can't find a Livechat method to do so.
https://docs.rocket.chat/guides/developer-guides/rest-api/livechat

There is no problem in sending text only messages.

**Comment by dudanogueira** [comment]
Can confirm that. There is no documentation, and the API code is here:

https://github.com/RocketChat/Rocket.Chat/blob/0f36b36ca4046b152d0ddb42ca80d0b29afa0555/app/livechat/imports/server/rest/upload.js#L21

Also, as of 3.18.1 (not sure if it was introduced at this version), the endpoint will give a error (500) even when it works fine.

```
rocketchat_1 | TypeError: Cannot read property ‘statusCode’ of undefined
rocketchat_1 | at Array. (app/api/server/api.js:415:139)
rocketchat_1 | at Logger._log (app/logger/server/server.js:286:27)
rocketchat_1 | at Logger. [as info] (app/logger/server/server.js:101:22)
rocketchat_1 | at Object._internalRouteActionHandler [as action] (app/api/server/api.js:415:13)
rocketchat_1 | at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
rocketchat_1 | at packages/nimble_restivus/lib/route.coffee:59:33
rocketchat_1 | at packages/simple_json-routes.js:98:9
```

**Comment by Faria1212** [comment]
Hi guys, We are using that api to test candidates for the technical writer position, hence no documentation. But I can still help you with documentation via email. Please let me know @ValerioCietto
