### ISSUE TITLE
Broken links in Livechat API root

### ISSUE THREAD

**Issue by Fishbowler** [RocketChat/docs-old#1755]
https://github.com/RocketChat/docs/blob/master/guides/developer-guides/rest-api/livechat/README.md

Some of these links direct to pages within specific GitHub commits (that are missing) rather than relative links to other pages.

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/docs/commit/f35c6a34b7e1c4346057e79658cf881b14feee8b
