### ISSUE TITLE
[Broken link] in /installation/manual-installation/redhat

### ISSUE THREAD

**Issue by 6uhrmittag** [RocketChat/docs-old#1757]
The link in 

> You can get started by reading Rocket.Chat Technical Implementation Guide for our Certified Container

is broken(404).

Broken URL: https://docs.rocket.chat/installation/manual-installation/redhat/Rocket.Chat%20Technical%20Implementation%20Guide%20v.20180316.pdf

**Comment by engelgabriel** [comment]
Fixed on https://github.com/RocketChat/docs/commit/f3e5f3710e82ca9c693d63facce2257a904a94d3
