### ISSUE TITLE
Eks documentation out of date

### ISSUE THREAD

**Issue by tkreque** [RocketChat/docs-old#1764]
https://github.com/RocketChat/docs/blob/master/installation/paas-deployments/aws/eks/README.md

Hi guys,

The documentation for the EKS deployment is out of date since AWS updated the Aws-cli to version 2 and Helm was updated to version 3 and some of the commands listed are decommissioned (_helm init_ and _aws ecr get-login_).

```
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
$ aws --version
aws-cli/2.0.29 Python/3.7.3 Linux/5.0.0-38-generic botocore/2.0.0dev33
```

Could you guys check and update this section?

**Comment by mkherlakian** [comment]
I ran into this today as well. Further research seems to suggest that tiller is removed in helm >3.0 (https://github.com/helm/helm/issues/6996). What is the best way around this?

**Comment by Rodriq** [comment]
ref #1858 
This requires you to [add the stable chart repository ](https://helm.sh/docs/intro/quickstart/#initialize-a-helm-chart-repository)to your Helm 3 instance.

See docs https://docs.rocket.chat/quick-start/scaling-rocket.chat/automation-tools/kubernetes-using-helm
