### ISSUE TITLE
Custom fields not working

### ISSUE THREAD

**Issue by flaviogoncalves** [RocketChat/docs-old#1773]
I tried everything possible, but still does not work. I´m using the Digital Ocean Image. 

Custom fields to show in user info 

[{"SIP Extension":"sip_extension"},{"SIP Password":"sip_password"}]

Custom fields in registration

{
	"sip_password": {
		"type": "text",
		"required": false,
		"minLength": 8,
		"maxLength": 12
	},
	"sip_extension": {
		"type": "text",
		"required": false,
		"minLength": 4,
		"maxLength": 5
	}
}

Fields do not appear in the user info. 

![image](https://user-images.githubusercontent.com/4958202/88850758-2e5e1600-d1c2-11ea-8fc5-3da5984f6db8.png)

**Comment by dudanogueira** [comment]
Hi!

Let us know if this still happens in our latest 6.4.3 version. This is certainly not a doc issue, and it's definitely working.

If you still face this problem, please consider using our [Community Support Channel](https://open.rocket.chat/channel/support) for support.

Thanks!
