### ISSUE TITLE
Login authentication rocket chat

### ISSUE THREAD

**Issue by thanhtuyenpkk** [RocketChat/docs-old#1778]
Hi all, 
I had read 
https://docs.rocket.chat/guides/developer/embedded-layout
https://docs.rocket.chat/guides/developer/iframe-integration/authentication
I'm Embedded Layout rocketchat to my project reactjs. but if not login it will return to login page.
And I try Iframe Integration but don't know how.

My code 

> componentDidMount() {
>         let b = document.getElementById('rcChannel').contentWindow;
>         b.postMessage({
>             event: 'login-with-token',
>             loginToken: 'AQ2plmfrf1p75BZkYV0KckcCnP9xvJT-zgQ6ajiJqlN'
>         }, 'https://rocket.com/');
>         // window.parent.postMessage({
>         //     event: 'login-with-token',
>         //     loginToken: 'AQ2plmfrf1p75BZkYV0KckcCnP9xvJT-zgQ6ajiJqlN'
>         // }, 'https://rocket.com/');
>     }

>  render() {
>         return (
>             <Iframe url="https://rocket.com/group/room1?layout=embedded"
>                 target="_parent"
>                 width="450px"
>                 height="450px"
>                 id="rcChannel"
>                 display="initial"
>                 position="relative"
>                 />
>         );
>     }

https://rocket.com/ is my domains
If I have use this code it allway return to login page and console log is 

> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://rocket.com') does not match the recipient window's origin ('http://localhost:3000').

Here any body can help me how to implement it
thanks you

**Comment by dudanogueira** [comment]
Hi! This is not an issue, rather a support request.

Please, consider using our Community [Support Channel](https://open.rocket.chat/channel/support) or [Forums](https://forums.rocket.chat/) if you still face this error.

Thanks!
