### ISSUE TITLE
Update procedure for rocketchat multiple instances on multiple nodes

### ISSUE THREAD

**Issue by thetthet7** [RocketChat/docs-old#1783]
I would like to update my rocketchat 3.5.2 instances to 3.6.0 and I'm looking solution for multiple instances on multiple nodes.

I found only single update like below.
https://docs.rocket.chat/installation/manual-installation/updating

Let me know if you have better way with minimum downtime.

Thanks.

**Comment by Rodriq** [comment]
There is no specific recommendation here perse. You should be able to update with minimum downtime.
