### ISSUE TITLE
Azure documentation?

### ISSUE THREAD

**Issue by NadavBH** [RocketChat/docs-old#1790]
Will there be an Azure documentation?
Hosting RocketChat on AKS and/or Azure Virtual Machines with Azure DNS?

Thank you.

**Comment by MJPGPleasant** [comment]
To add to this - Azure Authentication Configuration. (OAuth2 and SAML)

**Comment by Rodriq** [comment]
OAuth2 docs https://docs.rocket.chat/guides/administration/admin-panel/settings/oauth/ms-office-365-oauth-setup
