### ISSUE TITLE
Error when try LDAP sync

### ISSUE THREAD

**Issue by tomalex1978** [RocketChat/docs-old#1792]
Ubuntu 18.04

Rocket.Chat
Версия	3.6.2
Версия движка приложений	1.17.0
Миграция базы данных	205

Среда выполнения
Тип ОС	Linux
Платформа ОС	linux
Архитектура ОС	x64
Версия ОС	5.4.0-47-generic
Версия Node	v12.14.0
Mongo версия	4.0.20
Mongo Storage Engine	mmapv1
Время работы ОС	2 часы, 49 минуты, 1 секунды
Среднее загрузка ОС	0.00, 0.00, 0.00
Общее кол-во памяти в ОС	7.77 GB
Свободное количество памяти	5.35 GB
Количество процессоров в ОС	2

when try LDAP sync:

I20200922-13:59:12.623(7) server.js:204 LDAP ➔ Connection.error connection Error: read ECONNRESET     at TCP.onStreamRead (internal/stream_base_commons.js:201:27) {   errno: 'ECONNRESET',   code: 'ECONNRESET',   syscall: 'read' } 
I20200922-14:00:00.085(7) server.js:204 LDAPSync ➔ error errorClass [Error]: File size (size = 0) is too small (min = 1) [file-too-small]     at Object.fileTooSmallError (packages/jalik:ufs/ufs-filter.js:43:53)     at Filter.check (packages/jalik:ufs/ufs-filter.js:89:28)     at FileUploadClass.insert (app/file-upload/server/lib/FileUpload.js:586:11)     at DDPCommon.MethodInvocation.<anonymous> (app/ldap/server/sync.js:418:15)     at packages/dispatch_run-as-user.js:211:14     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)     at syncUserData (app/ldap/server/sync.js:417:11)     at app/ldap/server/sync.js:575:6     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1138:16)     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)     at sync (app/ldap/server/sync.js:565:10)     at Object.job (app/ldap/server/sync.js:605:5)     at packages/littledata_synced-cron.js:251:26     at scheduleTimeout (packages/littledata_synced-cron.js:304:9)     at packages/littledata_synced-cron.js:356:42     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24) {   isClientSafe: true,   error: 'file-too-small',   reason: 'File size (size = 0) is too small (min = 1)',   details: undefined,   message: 'File size (size = 0) is too small (min = 1) [file-too-small]',   errorType: 'Meteor.Error' } 
I20200922-14:00:00.495(7) Exception in callback of async function: errorClass [Error]: File size (size = 0) is too small (min = 1) [file-too-small]     at Object.fileTooSmallError (packages/jalik:ufs/ufs-filter.js:43:53)     at Filter.check (packages/jalik:ufs/ufs-filter.js:89:28)     at FileUploadClass.insert (app/file-upload/server/lib/FileUpload.js:586:11)     at DDPCommon.MethodInvocation.<anonymous> (app/ldap/server/sync.js:418:15)     at packages/dispatch_run-as-user.js:211:14     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)     at syncUserData (app/ldap/server/sync.js:417:11)     at addLdapUser (app/ldap/server/sync.js:469:2)     at app/ldap/server/sync.js:529:5     at Array.forEach (<anonymous>)     at app/ldap/server/sync.js:496:13     at runWithEnvironment (packages/meteor.js:1286:24) {   isClientSafe: true,   error: 'file-too-small',   reason: 'File size (size = 0) is too small (min = 1)',   details: undefined,   message: 'File size (size = 0) is too small (min = 1) [file-too-small]',   errorType: 'Meteor.Error' }

**Comment by Rodriq** [comment]
What are you trying to run LDAP sync with?

**Comment by Rodriq** [comment]
See LDAP documentation here https://docs.rocket.chat/guides/administration/admin-panel/settings/ldap/ldap-sync-settings
