### ISSUE TITLE
Duplication of some documentation

### ISSUE THREAD

**Issue by RohitKumar-200** [RocketChat/docs-old#1805]
### 3. https://rocket.chat/server-lookup is similar to https://docs.rocket.chat/legal/server-lookup

In first two cases
* Same content is written twice
* links on left hand side have content which is not readable(due to color combinations) , in fact we don't need these pages anymore
* link on left hand side should redirect to link on right hand side like other links do (In below screenshot)

## Visual representation of issue
![issue](https://user-images.githubusercontent.com/55583961/95896055-51539b80-0da9-11eb-95e6-adb42a6d9445.png)

In third case, pages are similar, but https://docs.rocket.chat/legal/server-lookup lacks functionality
![server_lookup](https://user-images.githubusercontent.com/55583961/95897592-6e896980-0dab-11eb-8185-4e144e046239.png)

## Proposed solution
1. All content inside https://rocket.chat/code-of-conduct should be deleted and this link should redirect to https://docs.rocket.chat/legal/code-of-conduct
2. All content inside https://rocket.chat/censorship-and-harmful-content/ should be deleted and this link should redirect to https://docs.rocket.chat/legal/censorship-and-harmful-content
3. https://docs.rocket.chat/legal/server-lookup should be added functionality similar to https://rocket.chat/server-lookup, and after that deleting content of https://rocket.chat/server-lookup and redirecting this link to https://docs.rocket.chat/legal/server-lookup.

**Comment by RohitKumar-200** [comment]
I want to work on this issue, but I am not able to find repository associated with https://rocket.chat/code-of-conduct

**Comment by ChristySujitha** [comment]
<img width="960" alt="serverlookup" src="https://user-images.githubusercontent.com/102861715/166654743-b8dcc49e-57c1-44ea-b47d-30d7982b6193.png">
<img width="960" alt="serverlookuplegal" src="https://user-images.githubusercontent.com/102861715/166654762-b4801395-0ba7-4353-809c-ed656c6322e7.png">

**Comment by ChristySujitha** [comment]
<img width="960" alt="censorshippagenotfound" src="https://user-images.githubusercontent.com/102861715/166654917-56131dff-9189-4151-84b0-8e7e3219d862.png">
<img width="960" alt="censorshippage" src="https://user-images.githubusercontent.com/102861715/166654927-6627870b-0fc9-444c-becc-200a8050f130.png">

**Comment by ChristySujitha** [comment]
<img width="960" alt="codeofconductpagenotfound" src="https://user-images.githubusercontent.com/102861715/166654985-f0d92225-4e1d-4e78-b552-3b1cff8fc91d
<img width="960" alt="codeofconductpage" src="https://user-images.githubusercontent.com/102861715/166654995-3aa40455-6206-4415-84aa-238d50c6090a.png">
.png">

**Comment by ChristySujitha** [comment]
![Uploading codeofconductpagenotfound.png…]()
<img width="960" alt="codeofconductpage" src="https://user-images.githubusercontent.com/102861715/166655199-9e699980-6f29-4e1e-a058-580ea11789f6.png">

**Comment by ChristySujitha** [comment]
<img width="960" alt="codeofconductpagenotfound" src="https://user-images.githubusercontent.com/102861715/166655364-ffcbb915-1302-498f-9878-15ce5ea2a842.png">

**Comment by ChristySujitha** [comment]
<img width="960" alt="codeofconductpage" src="https://user-images.githubusercontent.com/102861715/166655411-8f5dc643-fba2-424c-8746-3b1da6f26e91.png">

**Comment by ChristySujitha** [comment]
> ## Some pages in rocket.chat have exact same content which docs.rocket.chat have
> ### 1. https://rocket.chat/code-of-conduct is similar to https://docs.rocket.chat/legal/code-of-conduct
> ### 2. https://rocket.chat/censorship-and-harmful-content/ is similar to https://docs.rocket.chat/legal/censorship-and-harmful-content
> ### 3. https://rocket.chat/server-lookup is similar to https://docs.rocket.chat/legal/server-lookup
> In first two cases
> 
> * Same content is written twice
> * links on left hand side have content which is not readable(due to color combinations) , in fact we don't need these pages anymore
> * link on left hand side should redirect to link on right hand side like other links do (In below screenshot)
> 
> ## Visual representation of issue
> ![issue](https://user-images.githubusercontent.com/55583961/95896055-51539b80-0da9-11eb-95e6-adb42a6d9445.png)
> 
> In third case, pages are similar, but https://docs.rocket.chat/legal/server-lookup lacks functionality ![server_lookup](https://user-images.githubusercontent.com/55583961/95897592-6e896980-0dab-11eb-8185-4e144e046239.png)
> 
> ## Proposed solution
> 1. All content inside https://rocket.chat/code-of-conduct should be deleted and this link should redirect to https://docs.rocket.chat/legal/code-of-conduct
> 2. All content inside https://rocket.chat/censorship-and-harmful-content/ should be deleted and this link should redirect to https://docs.rocket.chat/legal/censorship-and-harmful-content
> 3. https://docs.rocket.chat/legal/server-lookup should be added functionality similar to https://rocket.chat/server-lookup, and after that deleting content of https://rocket.chat/server-lookup and redirecting this link to https://docs.rocket.chat/legal/server-lookup.

No duplicated documentation
