### ISSUE TITLE
FreeIPA LDAP users in rocketchat

### ISSUE THREAD

**Issue by rajivfx** [RocketChat/docs-old#1806]
I was using rocketchat with microsoft active directory. and all users are sync well.
Here is a video tutorial I created to show How to integrate Active Directory LDAP users in rocketchat.
https://www.youtube.com/watch?v=H8C5_ujWm2c

Now, I am trying to sync Centos 8 FreeIPA ldap users in rocketchat 3.7.0.
But not getting any users.
Any recommended settings for FreeIPA ?

**Comment by James6xie** [comment]
HI man i also met that issues , how did you resolved it ? thanks a lot !!!

**Comment by Rodriq** [comment]
Visit the LDAP docs https://docs.rocket.chat/guides/administration/admin-panel/settings/ldap/ldap-sync-settings
