### ISSUE TITLE
Auto SSL with Snaps

### ISSUE THREAD

**Issue by dsmagghe** [RocketChat/docs-old#1807]
AutoSSL with snaps does not work anymore.
In the automated process there is now a let's encrypt question asking for agreement on the general terms and conditions which is not answered by the automation process.
og files look like this:
Oct 15 10:30:07 rocketchat.tilaa.cloud rocketchat-server.rocketchat-caddy[7408]: Do you agree to the terms? (y/n):
Oct 15 10:30:07 rocketchat.tilaa.cloud rocketchat-server.rocketchat-caddy[7408]: Your sites will be served over HTTPS automatically using Let's Encrypt.
Oct 15 10:30:07 rocketchat.tilaa.cloud rocketchat-server.rocketchat-caddy[7408]: By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
Oct 15 10:30:07 rocketchat.tilaa.cloud rocketchat-server.rocketchat-caddy[7408]:   https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Oct 15 10:30:08 rocketchat.tilaa.cloud rocketchat-server.rocketchat-caddy[7408]: Do you agree to the terms? (y/n): 2020/10/15 10:30:08 user must agree to CA terms
Oct 15 10:30:08 rocketchat.tilaa.cloud systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Main process exited, code=exited, status=1/FAILURE
Oct 15 10:30:08 rocketchat.tilaa.cloud systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result 'exit-code'.
Oct 15 10:30:08 rocketchat.tilaa.cloud systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Service hold-off time over, scheduling restart.
Oct 15 10:30:08 rocketchat.tilaa.cloud systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Scheduled restart job, restart counter is at 150.
Oct 15 10:30:08 rocketchat.tilaa.cloud systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-caddy.
Oct 15 10:30:08 rocketchat.tilaa.cloud systemd[1]: Started Service for snap application rocketchat-server.rocketchat-caddy.
Oct 15 10:30:09 rocketchat.tilaa.cloud rocketchat-server.rocketchat-caddy[7463]: Activating privacy features...
Oct 15 10:30:09 rocketchat.tilaa.cloud rocketchat-server.rocketchat-caddy[7463]: Your sites will be served over HTTPS automatically using Let's Encrypt.
Oct 15 10:30:09 rocketchat.tilaa.cloud rocketchat-server.rocketchat-caddy[7463]: By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
Oct 15 10:30:09 rocketchat.tilaa.cloud rocketchat-server.rocketchat-caddy[7463]:   https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Oct 15 10:30:10 rocketchat.tilaa.cloud rocketchat-server.rocketchat-caddy[7463]: Do you agree to the terms? (y/n):
Oct 15 10:30:10 rocketchat.tilaa.cloud rocketchat-server.rocketchat-caddy[7463]: Your sites will be served over HTTPS automatically using Let's Encrypt.
Oct 15 10:30:10 rocketchat.tilaa.cloud rocketchat-server.rocketchat-caddy[7463]: By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
Oct 15 10:30:10 rocketchat.tilaa.cloud rocketchat-server.rocketchat-caddy[7463]:   https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf

**Comment by nthack** [comment]
I got the same problem since I manually install the caddy V1.0.3

**Comment by dudanogueira** [comment]
Hi!

As we have updated our snaps package, we doesn't haven seen this Issue.

Let us know in our [Community Support Channel](https://open.rocket.chat/channel/support) if you face this issue.

Thanks!
