### ISSUE TITLE
Update Caddy Reverse Proxy documentation for Caddy 2

### ISSUE THREAD

**Issue by dkoo761** [RocketChat/docs-old#1813]
Caddy 2 has been out for a few months now and the Caddy 1 config settings in the docs no longer work with it.

With Caddy 2, much of the config settings are now defaults and/or no longer needed.

On this page: https://docs.rocket.chat/installation/manual-installation/configuring-ssl-reverse-proxy#running-behind-a-caddy-reverse-proxy-with-free-ssl

Below this Caddy 1 config example...

```
your_domain.com {
        proxy / 127.0.0.1:3000 {
                header_upstream X-Forwarded-Proto {scheme}
                header_upstream X-Forwarded-For {host}
                header_upstream Host {host}
                websocket
        }
}
```

We should provide the equivalent Caddy 2 config:

```
your_domain.com {
        reverse_proxy localhost:3000
}
```

I'm using the above config for my production Rocket.Chat site with Caddy 2 on Ubuntu 18.04 and it's working perfectly.

**Comment by florisvangeel** [comment]
Caddy1 is indeed deprecated, i run a configuration like this on Ubuntu 20.04 for caddy2
```
yourdomain.com {
        reverse_proxy localhost:3000
        header Access-Control-Allow-Methods "POST, GET, OPTIONS"
        header Access-Control-Allow-Headers "*"
        import cors https://sub.domain.livechat
}
```
The CORRS headers are optional for liveschat.
Obviously if you poxy to an IP address in the LAN change localhost in the IP

**Comment by Faria1212** [comment]
The document was updated. Thank you @dkoo761 for your contribution.
