### ISSUE TITLE
Webhooks doc for graylog, update to 3.x

### ISSUE THREAD

**Issue by MatzeJoerling** [RocketChat/docs-old#1830]
Hi,
graylog api webhook https://docs.rocket.chat/guides/administrator-guides/integrations/graylog is only for very old 2.4 installations.
Graylog API hase change in version 3.x, the Webhook is not running anymore. 
Reflect that in the docs or perhaps - write a Webhook that is working with 3.x.
I know, make PR, but sorry - only a user without coding skills.

would really love tu use that webhook with really great Rocket.Chat!

regards M.

**Comment by dudanogueira** [comment]
The doc nowadays point to the above repo. 
Sent the PR to fix it for newer versions.

this Issue can be closed.
