### ISSUE TITLE
Debian install guide incorrect

### ISSUE THREAD

**Issue by shellster** [RocketChat/docs-old#184]
Debian install guide incorrectly states that there is no mongo 3.2 for jessie.  This is no longer true:
http://repo.mongodb.org/apt/debian/dists/jessie/mongodb-org/3.2/main/

**Comment by MartinSchoeler** [comment]
I dont see any mention to jessie on the debian install guide. It could been updated. If you still have a issue please open a new issue with updated details. Thanks!
