### ISSUE TITLE
Reset password docs are not through enough to be useful.

### ISSUE THREAD

**Issue by jleach** [RocketChat/docs-old#1846]
Password documentation is not helpful; or maybe its just not thorough.

This command works as per the docs, but it does not explain why other `bcrypt` passwords fails.
`db.getCollection('users').update({username:"administrator"}, { $set: {"services" : { "password" : {"bcrypt" : "$2a$10$n9CM8OgInDlwpvjLKLPML.eizXIzLlRtgCh3GRLafOdR9ldAUh/KG" } } } })`

For example, `htpasswd -bnBC 10 "" 12345 | tr -d ':\n' | sed 's/$2y/$2a/'` creates a legitimate bcrypt password. It won't work in the same command though.

**Comment by dudanogueira** [comment]
Hi!

It will follow meteor's password stack. 

You can generate a valid one with:

> npm install -g @carsondarling/bcrypt-cli
> bcrypt $(echo -n "yourPasswordHere" | sha256sum | cut -d " " -f 1) && echo

we can add this to the [restoring the admin password](https://docs.rocket.chat/guides/administration/misc.-admin-guides/restoring-an-admin), but the idea there is to set a temporary password, so the access can be restored and the password changed right away.

**Comment by Faria1212** [comment]
Please find the updated doc here https://docs.rocket.chat/guides/administration/advanced-admin-settings/restoring-an-admin
