### ISSUE TITLE
Kubernetes documentation not up-to-date

### ISSUE THREAD

**Issue by lupaulus** [RocketChat/docs-old#1858]
Hi,
I want to install Rocket Chat on K8s but the doncumentation seems outdated,

```installation/automation-tools/helm-chart.md```

Can someone update the documentation and the helm-chart because Helm3 shows that the chart is deprecated.

Thanks

**Comment by lupaulus** [comment]
I'am working on a version to deploy rocket chat on kubernetes

https://github.com/lupaulus/rocket-chat-kubernetes

**Comment by Rodriq** [comment]
Note to add stable chart repository https://docs.rocket.chat/quick-start/scaling-rocket.chat/automation-tools/kubernetes-using-helm
