### ISSUE TITLE
keycloak document photo missing

### ISSUE THREAD

**Issue by ibrahimyildizz** [RocketChat/docs-old#1860]
Can you please add again?

![User Role Mapping][User Role Mapping]

The roles are only synced on first login, and not being refreshed on each login. Please see the bug report for current state.

[User Role Mapping]: user_role_mapping.png
https://github.com/RocketChat/docs/blob/master/guides/administrator-guides/authentication/open-id-connect/keycloak.md

**Comment by JKawohl** [comment]
jupp this is giving me a headache.

**Comment by ibrahimyildizz** [comment]
If you wish, I can count mr with the method I apply. @JKawohl

**Comment by Faria1212** [comment]
Please find the doc here https://docs.rocket.chat/guides/administration/advanced-admin-settings/authentication/open-id-connect/keycloak
