### ISSUE TITLE
Can't host a local gitbook with this docs repo

### ISSUE THREAD

**Issue by HiChat-crew** [RocketChat/docs-old#1879]
Hi! I'm trying to create a local gitbook documentation of this project.
Though gitbook throws an error: 

error: error while generating page "installation/README.md"
Template render error: (/home/aviv/Documents/docs/installation/README.md) [Line 5, Column 2] 
unknown block tag: page

Can anyone create a guide or help me understand how I can load this repo in a local gitbook?

**Comment by engelgabriel** [comment]
We need to check if https://github.com/GitbookIO/gitbook/blob/master/docs/setup.md still works

**Comment by engelgabriel** [comment]
Looks like it has been depricated. We need to remove the install instructions.

**Comment by Rodriq** [comment]
`gitbook_cli` has been deprecated
contribution to the docs can still be done by simply editing the `.md` files. A guide on local environment setup is here https://docs.rocket.chat/contributors/how-can-i-help/documentation#environment-setup
