### ISSUE TITLE
[GSoC] List of ideas link redirects to 2018 idea page

### ISSUE THREAD

**Issue by aashrafh** [RocketChat/docs-old#1880]
The link of ```list of ideas``` in GSoC 2012 [page](https://github.com/RocketChat/docs/blob/master/contributors/gsoc/google-summer-of-code-2021.md) redirects to 2018 idea [page](https://github.com/RocketChat/docs/blob/master/contributors/gsoc/google-summer-of-code-2018.md#project-ideas). Is this valid or should be fixed? 

![Screenshot_20210215_200529](https://user-images.githubusercontent.com/40968967/107980790-8840f480-6fc9-11eb-8d4f-6e378d1d4b6a.png)

**Comment by Sing-Li** [comment]
fixed. thanks.
