### ISSUE TITLE
Sync problem with GitBook and GitHub

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/docs-old#1904]
Sometimes, when you turn a single page into a section in GitBook, you may get an error when syncing with GitHub.

The file `article-title.md` gets converted into a folder `article-title/README.md`, but the original file gets forgotten rather than deleted. This causes a lot of confusion. 

<img width="1792" alt="Screenshot 2021-03-09 at 14 41 47" src="https://user-images.githubusercontent.com/1000217/111350543-faf0ce80-8660-11eb-87a4-d4bf1f81a166.png">

We must parse the `SUMMARY.md` index file and ensure all files that are not linked there are reviewed and deleted. 

<img width="1008" alt="Screenshot 2021-03-09 at 14 43 09" src="https://user-images.githubusercontent.com/1000217/111350521-f6c4b100-8660-11eb-9b99-55b47908e352.png">

Ideally, we should have a script to check this on every PR, so we keep this from happening again.

**Comment by Rodriq** [comment]
Currently on GitBook, turning a page to a higher hierarchy(folder) moves it with all its contents and the sync works fine along with updating the `SUMMARY.md`.

I also manually crosscheck the links in `SUMMARY` using Markdown Link Checker on Vscode and the indexing is correct.
If anything, we can open a new PR for a script to validate for any missing file `SUMMARY.md` file
