### ISSUE TITLE
Developer guide removed

### ISSUE THREAD

**Issue by MeghalBisht** [RocketChat/docs-old#1923]
The docs for developer guide were removed recently. Probably due to https://github.com/RocketChat/docs/commit/39dccc681318256780228f1b4854fa6a68412c62

Can they be added back?

Affected page- 
https://docs.rocket.chat/api/rest-api/methods/groups/invite
https://docs.rocket.chat/api/rest-api/methods/groups/info
etc

**Comment by zfha** [comment]
I found out today too, why

**Comment by ngoue** [comment]
All the REST API docs are gone.  So help me if you're planning on removing support for using the REST API hahaha.

**Comment by juanjoku** [comment]
And bots guides ... :_(

**Comment by iamareebjamal** [comment]
https://developer.rocket.chat/

**Comment by Faria1212** [comment]
Our developer docs have a home of their own now!! Please find them here https://developer.rocket.chat/
