### ISSUE TITLE
ALL API DOCS GONE?

### ISSUE THREAD

**Issue by HiveMindNet** [RocketChat/docs-old#1924]
Was it intentional to remove from public viewing all REST API documentation? Or has it moved somewhere I can't find?

Google now points to a 'page not found'?

**Comment by HiveMindNet** [comment]
Looks like it's all been deleted by @Faria-TechWrite  - can you shed any light on this please?

**Comment by Faria1212** [comment]
Hi,
Faria from Techincal Writing. Our developer docs have a home of their own
now!! Please find them here https://developer.rocket.chat/
Sorry for the inconvenience.

**Comment by HiveMindNet** [comment]
Phew! Maybe some redirects and telling folk what's happening might prevent a bit of panic! :)

**Comment by Faria1212** [comment]
Yes. Thanks for the tip!!

**Comment by robincafolla** [comment]
@Faria-TechWrite  Is there a git repo for the developer docs? I note that you can no longer edit the dev docs in github; is that intended?

**Comment by Faria1212** [comment]
Yes, they are. https://github.com/RocketChat/developer-docs
