### ISSUE TITLE
Write ldap documentation

### ISSUE THREAD

**Issue by scoopex** [RocketChat/docs-old#193]
The ldap documentation currently only provides examples for configuring ldap but not a detailed information what functionality is behind the various configuration options.

From my point of view it would be good to have detailed information about the options i the application itself or as an addition to https://rocket.chat/docs/administrator-guides/authentication/ldap/

**Comment by Faria-TechWrite** [comment]
@MartinSchoeler are they still to be done? I couldn't find anything on it on docs. If it's still necessary please open a task here when you get time. And also paste the link to this issue in it. https://app.clickup.com/4207297/v/l/6-7470802-1?pr=3058186
