### ISSUE TITLE
Page not found 404

### ISSUE THREAD

**Issue by lupael** [RocketChat/docs-old#1930]
### Description:

Wrong link from RocketChat website https://rocket.chat/bots/ 

### Steps to reproduce:

1. Go to https://rocket.chat/bots/
2. Click on Quick Start Guide Hubot , Botkit, Rasa bot and botpress bot
3. Those link goes to wrong page where shows page not found 404 errors https://docs.rocket.chat/bots/create-and-run-a-bot/hubot-bot

### Expected behavior:
Correct url is https://docs.rocket.chat/guides/bots/running-a-hubot-bot

### Actual behavior:

![Screenshot_2021-04-20-04-57-16-214_com android chrome](https://user-images.githubusercontent.com/43011721/115313347-e7bbac00-a194-11eb-8d5a-de876ff89400.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Faria1212** [comment]
@juliagrala please ask your team to review it. Thanks

**Comment by soham4abc** [comment]
https://docs.rocket.chat/guides/bots/running-a-hubot-bot
This link also shows 404 error.
I would like to work on this issue but need the correct link which needs to be replaced

**Comment by soham4abc** [comment]
> https://docs.rocket.chat/guides/bots/running-a-hubot-bot
> This link also shows 404 error.
> I would like to work on this issue but need the correct link which needs to be replaced

@Faria-TechWrite  this is not yet resolved!

**Comment by Faria1212** [comment]
Please refer to this link instead. https://developer.rocket.chat/guides/bots-guides/create-and-run-a-bot Thank you for opening this issue. We will update the links on the website asap

**Comment by soham4abc** [comment]
> Please refer to this link instead. https://developer.rocket.chat/guides/bots-guides/create-and-run-a-bot Thank you for opening this issue. We will update the links on the website asap
> 

I am willing to work on this issue. Can I? If possible pls assign! Thank you!

**Comment by lupael** [comment]
> > Please refer to this link instead. https://developer.rocket.chat/guides/bots-guides/create-and-run-a-bot Thank you for opening this issue. We will update the links on the website asap
> 
> I am willing to work on this issue. Can I? If possible pls assign! Thank you!

@soham4abc  Yes possible, if you know how to. @Faria-TechWrite four month gone but no response from @juliagrala maybe she's busy @geekgonecrazy please appoint few people to this group

**Comment by Faria1212** [comment]
Please check now @lupael

**Comment by lupael** [comment]
Same 404 @Faria-TechWrite 
![image](https://user-images.githubusercontent.com/43011721/149656880-5faf40e5-0011-46d2-b09a-0f85b4d2dfd6.png)

**Comment by Faria-TechWrite** [comment]
https://app.gitbook.com/o/-M41dOPtnjO7qK6KCyrt/s/-MWf1K8RJU-TjNEtPxvb/bots/creating-your-own-bot-from-scratch

**Comment by Faria1212** [comment]
https://developer.rocket.chat/bots/creating-your-own-bot-from-scratch
