### ISSUE TITLE
Message formatting doc is incomplete

### ISSUE THREAD

**Issue by lkraider** [RocketChat/docs-old#1993]
There seems to be more formatting options than described in the docs as per https://github.com/RocketChat/docs/pull/1120

For example, triple quoting allow multi-line code formatting, along with specifying language for syntax highlight:

    ```python
    while True:
         print "make better user docs"
    ```

What other options are available? Would be great if users could access a doc form within the chat to know what they can use when composing messages.

**Comment by juniopereirab** [comment]
I made some changes in this document and submitted them. I notice that in RocketChat messages, we cannot use the language to complement the block code, like you did with "python". So I didn't put this in the example.

**Comment by lkraider** [comment]
I double checked, and indeed it is probably because the parser is set as `Marked` for my instance in `Administration -> Message -> Markdown -> Markdown Parser` that more formatting options are available. Maybe mention in the docs that this is something that can be enabled?
![Screen Shot 2021-08-17 at 09 55 17](https://user-images.githubusercontent.com/52256/129729367-ffa1b0e0-3042-4810-9b63-1e78c050b6dc.png)

**Comment by juniopereirab** [comment]
Hmm.. I think it's able to be added to the documentation guide. I can't follow these steps through Administration since I just started to use RocketChat to contribute on OpenSource and I don't have any configuration and access at Administration section yet.

I saw that RocketChat already have Admin Settings about Messages in this link: https://docs.rocket.chat/guides/administration/administration/settings/message

Maybe that link can be added to user guide as a complement.

**Comment by juniopereirab** [comment]
By the way, the link above seems to be under development too.

**Comment by ChristySujitha** [comment]
Please refer to this link: https://docs.rocket.chat/guides/administration/admin-panel/settings/message#markdown. it works fine.

**Comment by ChristySujitha** [comment]
> I double checked, and indeed it is probably because the parser is set as `Marked` for my instance in `Administration -> Message -> Markdown -> Markdown Parser` that more formatting options are available. Maybe mention in the docs that this is something that can be enabled? ![Screen Shot 2021-08-17 at 09 55 17](https://user-images.githubusercontent.com/52256/129729367-ffa1b0e0-3042-4810-9b63-1e78c050b6dc.png)

Added
