### ISSUE TITLE
To use the WhatsApp by Rocket.chat do i need a cellphone?

### ISSUE THREAD

**Issue by solanha1999** [RocketChat/docs-old#1998]
To use the WhatsApp by Rocket.chat do i need a cellphone?
I want to know how I log into the whatsapp account that I want to connect with this app?

**Comment by ruvenss** [comment]
You can use our integration [https://rgwit.be/en/products/rocketchat/whatsapp/](https://rgwit.be/en/products/rocketchat/whatsapp/)

**Comment by dudanogueira** [comment]
hi @solanha1999

Please, check this doc for more information:
https://docs.rocket.chat/resources/frequently-asked-questions/whatsapp-business-app-faqs
