### ISSUE TITLE
Separation of Hangul consonants and vowels on typing

### ISSUE THREAD

**Issue by on-future** [RocketChat/docs-old#2000]
![Screen Shot 2021-08-02 at 5 57 49 PM](https://user-images.githubusercontent.com/10277106/127833967-9ea8b779-92be-493e-8fab-8dba054121e9.png)

- Broken consonants and vowels

![Screen Shot 2021-08-02 at 5 58 05 PM](https://user-images.githubusercontent.com/10277106/127834086-e651121f-d386-4f15-8477-6c19851c127d.png)

- Can't change label of registration form

**Comment by dudanogueira** [comment]
Hi!

This is certainly not a doc issue.

As our translations have changed, please, let us know if you still face this problem on latest 4.6.3

Thanks!
