### ISSUE TITLE
Install notes?

### ISSUE THREAD

**Issue by killmasta93** [RocketChat/docs-old#2015]
Hi 
I was wondering if someone could shed some light, the installation guide is not very clear on installing on rocket.chat 3.3.3 
not sure why i have seen the installation way by running 
`
 npm i @rocket.chat/livechat`

**Comment by dudanogueira** [comment]
Hi!

Please, refer to this doc:
https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods

Our suggested way of deployment is Docker or K8s.
