### ISSUE TITLE
High Availability deployment

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/docs-old#2037]
See

https://github.com/RocketChat/Rocket.Chat/issues/520
https://github.com/RocketChat/Rocket.Chat/issues/847
https://github.com/RocketChat/Rocket.Chat/issues/1867
https://github.com/RocketChat/Rocket.Chat/issues/2964

**Comment by Rodriq** [comment]
Docs for high availability here https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/docker-and-docker-compose/docker-containers/high-availability-install
