### ISSUE TITLE
document didn't explain how to add Token for rocketchat server installed through snap

### ISSUE THREAD

**Issue by overseers-desk** [RocketChat/docs-old#2044]
# Problem 1: Guide assumes server-UI

1. Install using snap and get rocketchat-server working. Verify by connecting through rocketchat-deskto†.
2. Read https://docs.rocket.chat/guides/administration/administration/connectivity-services and get the Token copied to the clipboard
3. The above doc then asks:
 
> On your Rocket.Chat server, go to Administration > Connectivity Services. Fill up the "Email" field with the email related to your Rocket.Chat Cloud account and in the "Token" field please paste the registration token generated. Finally, hit the "Connect" button.

I imagine in Windows installation there is a GUI for Rocket.Chat server that has an "Administration" section. The problem is that in my case Rocket.Chat server doesn't have UI - most Linux server software doesn't. The document failed to mention or provide a link for this scenario.

# Problem 2: Guide didn't mention how to configure Token

Reading the relevant document

https://docs.rocket.chat/installing-and-updating/snaps

and not seeing mentioning of how to configure Token for the server. The guide however did describe how to configure port for the server, makes me believe it is also the right place to mention how to configure Token.

--

† Installation and run, in my case Ubuntu 20.04
````
$ sudo snap install rocketchat-server rocketcat-client
$ sudo systemctl start snap.rocketchat-server.rocketchat-mongo.service
$ sudo snap run rocketchat-server
Checking if oplog has been enabled, and enabling if not
MongoDB shell version v3.6.14
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("07e508b3-9cdd-433d-a49d-14f0f7af327d") }
MongoDB server version: 3.6.14
Checking if mongo featureCompatibilityVersion is correct, changing if not
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Setting default file store to GridFS
{"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 228","time":{"$date":1630390346124},"level":"info"}
Loaded the Apps Framework and loaded a total of 0 Apps!
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
➔ System ➔ startup
➔ +-----------------------------------------+
➔ |              SERVER RUNNING             |
➔ +-----------------------------------------+
➔ |                                         |
➔ |  Rocket.Chat Version: 3.17.2            |
➔ |       NodeJS Version: 12.22.1 - x64     |
➔ |      MongoDB Version: 3.6.14            |
➔ |       MongoDB Engine: wiredTiger        |
➔ |             Platform: linux             |
➔ |         Process Port: 3000              |
➔ |             Site URL: http://localhost  |
➔ |     ReplicaSet OpLog: Enabled           |
➔ |          Commit Hash: fe0e5e4356        |
➔ |        Commit Branch: HEAD              |
➔ |                                         |
➔ +-----------------------------------------+
Updating process.env.MAIL_URL
(node:132283) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

````

**Comment by Rodriq** [comment]
To set a registration token for your server, create any file ending in` .env` under `/var/snap/rocketchat-server/current/` with content:
`REG_TOKEN=<your token>`
Then restart your server
`sudo systemctl restart snap.rocketchat-server.rocketchat-server`

See docs 
- https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/snaps#configuration
- https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/snaps/snap-faq#how-do-i-set-rocket.chat-registration-token-on-snap
