### ISSUE TITLE
Requested Integrations Guides

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/docs-old#2049]
Here is a list of requested integrations 

- [x] **Pagerduty**: https://github.com/kajisaap/rocketchat-pagerduty
- [x] **BugSnag**:  https://docs.bugsnag.com/product/integrations/
- [x] **django-rocketchat-auth**: https://pypi.python.org/pypi/django-rocketchat-auth

**Comment by ChristySujitha** [comment]
Updated the documentation for Pagerduty and django-rocketchat-auth.
