### ISSUE TITLE
Update multi-instance docs for INSTANCE_IP tips

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/docs-old#2054]
https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/3.%20Installation/4.%20Manual%20Installation/Multiple%20Instances%20to%20Improve%20Performance/README.md

We need to include tips on making sure INSTANCE_IP is set if using docker.  Also stress the importance of the instances being able to talk to each other.  Reference the admin->info screen that shows instance inter-connect status.  Making sure can connect to all.

Also maybe importance of oplog being set.

Maybe a blurb like this to help people understand whats going on.

> Normal messages are saved to the db. Every instance is connected to oplog. So when that message is saved it then the other instances see that event in oplog. 
> 
> Events information that isn't really needed to persist. Like typing indicator / notify-user etc we connect between instances and broadcast that event to them.

**Comment by Rodriq** [comment]
Guide on setting `INSTANCE_IP` https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/docker-and-docker-compose/docker-containers/high-availability-install#create-rocket.chat-docker-container
