### ISSUE TITLE
Better workaround for OPENSSL_1.0.2 error

### ISSUE THREAD

**Issue by aberkvam** [RocketChat/docs-old#2058]
https://github.com/RocketChat/docs/blob/master/installation/manual-installation/ubuntu/snaps/README.md mentions an OpenSSL error:

> Please note: at the time of writing, mongorestore required openssl version 1.0.2 specifically. If you see an error like this - (...) version 'OPENSSL_1.0.2' not found (required by /snap/rocketchat-server/current/bin/mongorestore) - simply install the required openssl version to continue.

The problem seems to be that running mongorestore as specified in the instructions uses the system libraries instead of the snap libraries.  Specifying the libraries in the following way worked for me:

`sudo LD_LIBRARY_PATH=/snap/rocketchat-server/current/lib/x86_64-linux-gnu/ /snap/rocketchat-server/current/bin/mongorestore --db parties \
~/backup_data/var/snap/rocketchat-server/<version>/dump/parties/`

It may not be the best solution but it's better than the one given and it would have saved me a lot of time.

**Comment by Rodriq** [comment]
Configure SSL on your snap install https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/snaps/auto-ssl-with-snaps
