### ISSUE TITLE
Zapier Docs

### ISSUE THREAD

**Issue by JSzaszvari** [RocketChat/docs-old#207]
The invite link in this document has not worked for a few weeks - https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/5.%20Administrator%20Guides/Integrations/Zapier/README.md

https://zapier.com/dashboard/auth/oauth/return/App32270API/ takes you too a page that says "The page you're looking for doesn't exist."

I would rather update it than delete the whole page, Is there updated instructions or should I go ahead and remove the whole Zapier page?

**Comment by JSzaszvari** [comment]
paging @graywolf336 for your input

**Comment by JSzaszvari** [comment]
Also, I did a PR to update the page with some manual steps. Let me know if anything needs to be changed.

https://github.com/RocketChat/Rocket.Chat.Docs/pull/209

**Comment by graywolf336** [comment]
I commented on your pull request with the correct invite link, if you want to change it otherwise I'll go ahead and merge and then change it myself.

**Comment by graywolf336** [comment]
Closing as the Zapier link is now correct.

**Comment by rmdes** [comment]
It seems that the default zapier Auth app created by rocket.chat install has a wrong redirect URL
I tried to search what or where this URL could be but I don't have any working integration with Zapier to compare..right now connecting let's say RSS to Rocket.chat fails at the step of connecting one's personal instance to the zap. 
![screenshot_1](https://user-images.githubusercontent.com/12155003/50483199-f5a8fa00-09ea-11e9-9b11-8899a10f6aef.png)

**Comment by Bloinka** [comment]
> It seems that the default zapier Auth app created by rocket.chat install has a wrong redirect URL
> I tried to search what or where this URL could be but I don't have any working integration with Zapier to compare..right now connecting let's say RSS to Rocket.chat fails at the step of connecting one's personal instance to the zap.
> ![screenshot_1](https://user-images.githubusercontent.com/12155003/50483199-f5a8fa00-09ea-11e9-9b11-8899a10f6aef.png)

I'm seeing the same thing.  Figure anything out?
