### ISSUE TITLE
Move rocket.service.js into offical GitHub namespace

### ISSUE THREAD

**Issue by frdmn** [RocketChat/docs-old#24]
Currently located in @Sing-Li's repo: https://github.com/Sing-Li/bbug/blob/master/images/rocket.service.js

---

Also maybe we should add passing of `MAIL_URL` environment variable in there

**Comment by MartinSchoeler** [comment]
@frdmn The link provided gives a 404, is this still a issue?

**Comment by MartinSchoeler** [comment]
@frdmn what is the purpose of `rocket.service.js` file?

**Comment by MartinSchoeler** [comment]
I will close this for now. If this issue become relevant again please open a new and updated issue
