### ISSUE TITLE
Cannot disable Desktop notifications

### ISSUE THREAD

**Issue by swvajanyatek** [RocketChat/docs-old#247]
I just upgraded to Version 2.4.0, and under "My Account" --> "Messages"  --> "Desktop Notifications", I see they are enabled and they are definitely working.  However, I don't see anyway to disable them?

**Comment by jemus42** [comment]
You probably meant to post this issue under [RocketChat/Rocket.Chat](https://github.com/RocketChat/Rocket.Chat), as this is the repository of the docs?

**Comment by MartinSchoeler** [comment]
Please Reopen this on [RocketChat/Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) Thanks!
