### ISSUE TITLE
Slackbridge docs out of date

### ISSUE THREAD

**Issue by TheVons** [RocketChat/docs-old#248]
It appears that documentation for Slackbridge is out of date. How does this work?

https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/5.%20Administrator%20Guides/Import/Slack/SlackBridge.md

**Comment by MartinSchoeler** [comment]
@Vonnguru Could you point what part of the slackbridge docs are outdated? Thanks!

**Comment by MartinSchoeler** [comment]
I am closing this due lack of response, if the issue persists please open a new issue
