### ISSUE TITLE
Instructions how to reset lost administration user / password 

### ISSUE THREAD

**Issue by frdmn** [RocketChat/docs-old#25]
To quote @marceloschmidt from https://github.com/RocketChat/Rocket.Chat/issues/206#issuecomment-124926626: 

> [...]. If you run with ADMIN_PASS and ADMIN_EMAIL, server will look for an admin user or another user with provided e-mail. If none is found, admin user is inserted. We need to update README accordingly.

**Comment by frdmn** [comment]
To quote @marceloschmidt from https://github.com/RocketChat/Rocket.Chat/issues/206#issuecomment-124926626: 

> I've created this. If you run with ADMIN_PASS and ADMIN_EMAIL, server will look for an admin user or another user with provided e-mail. If none is found, admin user is inserted. We need to update README accordingly.

**Comment by mkauzlar** [comment]
how does one reset the admin password? (without the UI as the admin left and his email can't be used)

**Comment by marceloschmidt** [comment]
@mkauzlar if you have access to the database, it's easy to set yourself as admin so you can access the UI and reset their password. Just look for your user under the `users` collection and add `admin` to your `roles`.

**Comment by mkauzlar** [comment]
I tried using:

db.users.update({username:'myusername'}, {$push: {'roles.**global_roles**' : 'admin'}});

but I get:

WriteResult({
    "nMatched" : 0,
    "nUpserted" : 0,
    "nModified" : 0,
    "writeError" : {
        "code" : 16837,
        "errmsg" : "cannot use the part (roles of roles.**global_roles**) to traverse the element ({roles: [ \"user\" ]})"
    }
})

I'm sorry but I'm not familiar with mongo

**Comment by marceloschmidt** [comment]
why global_roles? just push it to roles.

**Comment by mkauzlar** [comment]
right, sorry I ran now:

db.users.update({username:'myusername'}, {$set: {'roles' : '[ "admin" ]'}});

which actually changed the my role to admin however when I login now I can't see any menu

**Comment by marceloschmidt** [comment]
Please, check your quotes.

`db.users.update({username:'myusername'}, {$set: {'roles' : [ "admin" ]}});`

**Comment by mkauzlar** [comment]
That was it, thank you.

**Comment by nasrulhazim** [comment]
Some steps I have take note today, I've put it on my gist - [Rocket.Chat: Reset User Details](https://gist.github.com/nasrulhazim/10da3980c0e096e85a488e5a97add360).

**Comment by rvraj** [comment]
@nasrulhazim your suggested link worked..!! thanks, buddy..!!

**Comment by askya** [comment]
From https://docs.rocket.chat/setup-and-configure/advanced-workspace-management/restoring-an-admin
Updating the Admin Password
To update the admin password, you can either use a one-time access token or update the admin password to a random string. 

    Using an access token will require the user to change his password.

db.getCollection('users').update({username:"administrator"}, {$set: { "services":{"loginToken":{"token":"some-token-id-that-you-will-use-to-login-once"}}, "requirePasswordChange":true} })
Then access http://{your server url}/login-token/some-token-id-that-you-will-use-to-login-once to log in.

    Alternatively, you can update the admin password to a random string. Using 12345 as an example of the password, use its hashed(bycrypt) value:

db.getCollection('users').update({username:"administrator"}, { $set: {"services" : { "password" : {"bcrypt" : "$2a$10$n9CM8OgInDlwpvjLKLPML.eizXIzLlRtgCh3GRLafOdR9ldAUh/KG" } } } })
Replace administrator with the appropriate username of the administrator on your server.
Restart your application container in case the new password is not accepted yet.
