### ISSUE TITLE
Add docs for managing settings via environment variables

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/docs-old#261]
Ref: https://github.com/RocketChat/Rocket.Chat/issues/5806

@RocketChat/core i'm not sure where to put this... So going to drop it here so at least its down somewhere.

## Set Setting
You can set any settings value via an environment variable.
```
FileUpload_Storage_Type=GoogleCloudStorage
```

## Overwrite Setting
You can overwrite any setting by setting an environment variable prefixed with: `OVERWRITE_SETTING_`
```
OVERWRITE_SETTING_FileUpload_Storage_Type=GoogleCloudStorage
```

## Block Settings
You can block a setting from being changed by specifying the `SETTINGS_BLOCKED` environment variable.  This is a comma separated list.  Any setting you want to block you need to add to this list.
```
SETTINGS_BLOCKED=FileUpload_Storage_Type,FileUpload_GoogleStorage_AccessId,FileUpload_GoogleStorage_Secret
```

**Even you as an admin will not be able to change this via the UI.  If you want to change the setting you will need to remove it from the list and reboot the server**

## Hide  Settings
You can hide settings from the client by using the `SETTINGS_HIDDEN` environment variable
```
SETTINGS_HIDDEN=FileUpload_GoogleStorage_AccessId,FileUpload_GoogleStorage_Secret
```

**Be careful with this setting some settings like `FileUpload_Storage_Type` are needed by the client so can not be hidden**

**Comment by PixelJonas** [comment]
I just stumbled upon this issue with the question
"Is there any list of environment variables and their corresponding setting? Or is there a way to find it out (other than crawling the source)?"

**Comment by geekgonecrazy** [comment]
right click the field in admin and inspect you'll see the name is the setting name :) no list currently
