### ISSUE TITLE
REST API documentation incorrect for updating settings

### ISSUE THREAD

**Issue by howellsd** [RocketChat/docs-old#277]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.3

The Rocket.Chat REST API documentation for updating Rocket.Chat settings example is incorrect:

https://rocket.chat/docs/developer-guides/rest-api/settings/update

Example has:

curl -H "X-Auth-Token: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq" 
-H "X-User-Id: aobEdbYhXfu5hkeqG" 
http://localhost:3000/api/v1/settings/Livechat_enabled 
-d '{ "value": true }'

but it should be this:

curl -H "X-Auth-Token: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq" 
-H "X-User-Id: aobEdbYhXfu5hkeqG" 
-H "Content-type:application/json" 
http://localhost:3000/api/v1/settings/Livechat_enabled 
-d '{ "value": true }'

w/o -H "Content-type:application/json" in the header, the passed in -d JSON body argument will not be correctly parsed, causing the call to fail. This is true for all settings update calls.

**Comment by Dschuli** [comment]
Similar inconsistencies found for Docs in RestAPI createToken (example result) vs RC Version 0.56.0; actual result structure matches login call (which is more consistent anyhow)

**Comment by geekgonecrazy** [comment]
@howellsd @Dschuli API is for sure changing a lot recently.  So our documentation is likely going to lean more towards representing 0.56.0 and newer and not older versions of the api.

@graywolf336 might be able to confirm, but I assume this endpoint has changed since 0.52.0 and has likely been updated to represent newer iterations of the endpoint

**Comment by graywolf336** [comment]
@Dschuli Can you provide an example? We accept pull requests for improving the docs, as changes sometimes happen from contributors and they don't update the documentation sadly

**Comment by Dschuli** [comment]
@graywolf336 
Docs on https://rocket.chat/docs/developer-guides/rest-api/users/createtoken read

```
Example Result

{
  "_id": "BsNr28znDkG8aeo7W",
  "authToken": "2jdk99wuSjXPO201XlAks9sjDjAhSJmskAKW301mSuj9Sk",
  "success": true
}
```
while what I I get on 0.56.0 is
```
{ data:  
   { 
      userId: 'c73TA3BHNm4afZCiL',
      authToken: 'LmgaTbdZyZEeFhdAc-LF-7LyZKCdvU79lNjH0iyinY1' 
   },
  success: true 
}
```

**Comment by MarcosSpessatto** [comment]
@howellsd, @Dschuli the docs were updated, please see [here](https://github.com/RocketChat/docs/blob/master/developer-guides/rest-api/users/createtoken/README.md), and this PR: #324.
