### ISSUE TITLE
Problems with amazon s3

### ISSUE THREAD

**Issue by tobias-f** [RocketChat/docs-old#294]
I have a problem with the amazon S3 setup.
I created a bucket (EU London), configured the S3 bucket name, AWSAccessKeyId and AWSSecretAccessKey and set up the CORS configuration according to the documentation like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

However, if I try to upload the I get an error:
![image](https://cloud.githubusercontent.com/assets/7669055/26026558/d3f8aace-37fd-11e7-8b51-991f23ef0e3a.png)

I am using the docker-compose setup running on linode.

The log files show no errors or anything...

Any clues what I am doing wrong?

**Comment by frdmn** [comment]
Can you please raise log level? (https://<host>/admin/Logs): 

- Loglevel: 2
- Show packet: true
- Show file name and line number: true

Then reproduce the problem and see if the logs show anything interesting (https://<host>/admin/view-logs)

**Comment by geekgonecrazy** [comment]
make sure if you put something in the acl section that its correct, also make sure you are properly specifying the region `-0` usually means something is incorrectly configured on the rocket.chat side.

**Comment by rrepolona** [comment]
Hi, 

i received an email from Amazon Web Service regarding "Securing Amazon S3 Buckets"
saying this " your Amazon S3 bucket access control lists (ACLs) are currently configured to allow access from any user on the Internet" 

is there any updates i need to do on my AWS ACL? my current CORS config is

` <?xml  version="1.0" encoding="UTF-8"?> `
` <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">`
` <CORSRule>`
`    <AllowedOrigin>*</AllowedOrigin>`
`    <AllowedMethod>PUT</AllowedMethod>`
`    <AllowedMethod>POST</AllowedMethod>`
`    <AllowedMethod>GET</AllowedMethod>`
`    <AllowedMethod>HEAD</AllowedMethod>`
`    <MaxAgeSeconds>3000</MaxAgeSeconds>`
`    <AllowedHeader>*</AllowedHeader>`
`</CORSRule>`
`</CORSConfiguration>`

**Comment by MartinSchoeler** [comment]
Closing this due lack of response from original author, if the problem persists please open a new issue. Thanks!
