### ISSUE TITLE
Disable 0.0.0.0 hosting with Snap install

### ISSUE THREAD

**Issue by samzhang111** [RocketChat/docs-old#295]
I installed rocket.chat the fast way, with Snap on an Ubuntu 16.04 server, and I have it running quickly. Yay!

Now the issue is after following the instructions for [configuring a reverse proxy](https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy), I'm still able to visit the chat server directly at `host_ip:3000`. I'd like to disable direct access, and only allow access through the reverse proxy.

It looks like if I had installed the entire system manually, I would have the ability to set `ROOT_URL`, but I don't see an option for configuring it from a snap.

Is there any way to set this up?

**Comment by geekgonecrazy** [comment]
Please see:https://github.com/RocketChat/Rocket.Chat/issues/7036
