### ISSUE TITLE
Update Realtime API docs for Send Message - Sending a file

### ISSUE THREAD

**Issue by kklimczak** [RocketChat/docs-old#320]
Hi.
I'm using own instance of rocket.chat - version 0.56.0
When I send file using directive rocketchat-upload like here https://rocket.chat/docs/developer-guides/realtime-api/method-calls/send-message#sending-a-file

I got a response: 
```json
{ 
"msg": "result", 
"id": "2", 
"error": {    
  "error": "Invalid directive",   
  "reason": "The directive rocketchat-uploads does not seem to exist",    
  "message": "The directive rocketchat-uploads does not seem to exist [Invalid directive]",    
  "errorType": "Meteor.Error"  
  }
}
```
Do you have solution for that?

Best regards

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
