### ISSUE TITLE
Missing docs about auth token expiration

### ISSUE THREAD

**Issue by Davide95** [RocketChat/docs-old#325]
There aren't infos about how to manage token expiration and how to know when it happens, especially on Realtime APIs.
How can I know when the token expiration happens? When it happens I've only to login in or I've to reconnect to the server first?

**Comment by Davide95** [comment]
@MartinSchoeler why did you closed this ticket? Does the documentation now have this information or what else? Just to know.

**Comment by MartinSchoeler** [comment]
@Davide95 Wasn't this issue closed on https://github.com/RocketChat/docs/pull/346 ?

**Comment by Davide95** [comment]
@MartinSchoeler yes that's my fault.... I thought there was another issue that I opened in the past and never resolved. I'm sorry :D

**Comment by filipef101** [comment]
@Davide95 @MartinSchoeler Hey, how can I know the time to live of the token realtime api mentions ttl of the token but not the rest api. I would like to either get it from the server response or know where in the rocketchat code base that is specified
