### ISSUE TITLE
Snap: Your connection to this site is not fully secure.

### ISSUE THREAD

**Issue by e-gautier** [RocketChat/docs-old#328]
Hello,

So I set up a Rocketchat snap on Ubuntu 16.04 using AutoSSL (https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/3.%20Installation/4.%20Manual%20Installation/Ubuntu/Snaps/AutoSSL.md) 

and i get in Chrome :

<a href="http://imgur.com/B5DXstM"><img src="http://i.imgur.com/B5DXstM.png" title="source: imgur.com" /></a>

Caddyfile:
```
https://xxx.xxx:8080 {
  proxy / localhost:3000 {
    websocket
    transparent
  }
}
```

Did I miss something ?

**Comment by e-gautier** [comment]
OK I figured out that RocketChat is simply requesting external resources which are not private. That's all. Closing.

**Comment by localguru** [comment]
See #7490

**Comment by engelgabriel** [comment]
See https://github.com/RocketChat/feature-requests/issues/785
