### ISSUE TITLE
More Info on Minimum Hardware Requirements 

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/docs-old#332]
Looking at the following page for minimum hardware requirements:
https://rocket.chat/docs/installation/minimum-requirements

Questions: 
1. This was last updated almost a year ago.  Are these recommended minimum specs still valid, or should they be updated?

2. The specs don't mention anything about installations using multiple Rocket Chat service instances running on a machine.  If a organization was running more than one instance, would that impact these specs?

3. The specs don't mention anything about organizations running Mongo with replication.  Would that impact these specs?

4. If an organization was looking to purchase a bare-metal server for their RC installation, do they they only need the bare metal server for the machine running the RC services?  Or do they need additional bare metal servers for each Mongo server?

**Comment by Faria1212** [comment]
https://docs.rocket.chat/installing-and-updating/minimum-requirements-for-using-rocket.chat
