### ISSUE TITLE
Clean up large amount of half-baked / old documentation

### ISSUE THREAD

**Issue by antgel** [RocketChat/docs-old#334]
So many of the Docs are either:

1. Useless / old 
2. Useless / a list of commands without meaningful context
3. Duplicated
4. Illogically ordered.

Is anyone intending to run through and cleanup?

**Comment by vcapretz** [comment]
hey @antgel, can you point some examples for the categories you listed? I think this way we can get a better sense of what exactly need to be done!

**Comment by antgel** [comment]
See PR #337 for a good idea of where I'm coming from, and explanation of my current lack of time for RC work. I'm not especially happy that that PR was closed, but it's not my call. There are so many examples, it would be quicker (but not quick) to edit all the docs.

**Comment by vcapretz** [comment]
hey @antgel, nice! I'll check it and see where I can help!

**Comment by MartinSchoeler** [comment]
@antgel We are currently on the process of reorganizing the docs, so i will close this issue. If you find irrelevant or outdated docs, you can open separate issues, so it is easier to track. Thanks!

**Comment by antgel** [comment]
I noticed, and they're really looking better! :ok_hand:
