### ISSUE TITLE
Home-baked doc generator problematic

### ISSUE THREAD

**Issue by antgel** [RocketChat/docs-old#335]
The left column doesn't display / hide subheadings. The chapter pages are blank. Projects like Slate and Daux do it so much better - why don't we move to them?

**Comment by MartinSchoeler** [comment]
We have changed to Jekyll now and we are gradually improving the documentation layout and structure, so for now i will close this issue. If you find any problems with the new documentation, please create a new issue. Thanks for the feedback!
