### ISSUE TITLE
Use mdl to fix long lines and other style issues

### ISSUE THREAD

**Issue by antgel** [RocketChat/docs-old#336]
Suggest implementing some sort of coding standard for future contributions, including limiting line length.

In edit: How about some [markdownlint](https://github.com/markdownlint/markdownlint)? I just ran it, and it found 4165 issues. :(

**Comment by vcapretz** [comment]
we will need to install it globally https://github.com/igorshubovych/markdownlint-cli and add a `.markdownlint.json` file to the project so we can keep rules consistent.

**Comment by MartinSchoeler** [comment]
@antgel We are now running markdownlint on our travis pull request builds
