### ISSUE TITLE
Create doc for oauth2 o365

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/docs-old#338]
https://github.com/RocketChat/Rocket.Chat/issues/6809 one of our community members has pretty much laid all details out.  We just need to build a doc from it

**Comment by MartinSchoeler** [comment]
Moved to the [Documentation Map](https://github.com/RocketChat/docs/blob/master/contributing/documentation/documentation-map/README.md) in https://github.com/RocketChat/docs/pull/555
