### ISSUE TITLE
Mobile SDK methods requirements

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/docs-old#339]
*All “\*” methods are subscriptions*

## Socket Connection
The SDK needs to implement and handle all the socket connection with SSL servers.

## Authentication
The SDK needs to implement the authentication and signup with all this methods:

- [x] [Email](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/login)
- [x] [Username](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/login)
- [ ] Facebook
- [ ] Google
- [ ] Twitter
- [ ] GitHub
- [ ] LDAP

Also:
- [ ] Logout

## Subscriptions
- [ ] *List user subscriptions (DMs, Private Groups, Public Channels)
- [x] [Create a new channel](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/create-channels)
- [ ] Create a new DM
- [x] [Create a new Private Group](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/create-private-groups)
- [x] [Join a Channel](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/joining-channels)
- [x] [Exit a Channel/Private Group (except for owner)](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/leaving-rooms)
- [ ] Get Room information about Channel/Private Group
- [x] [Favorite a Room](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/favoriting-rooms)
- [ ] Show members list
- [ ] Show starred messages
- [ ] Show files
- [ ] Search subscriptions

## Messages
- [x] [Get history of messages](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/load-history)
- [x] *[List of messages in a room](https://rocket.chat/docs/developer-guides/realtime-api/subscriptions/stream-room-messages)
- [x] [Send a message](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/send-message)
- [x] [Edit a message](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/update-message)
- [ ] Upload file
- [x] [Star a message](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/star-message)
- [x] [Pin a message](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/pin-message)
- [ ] Unstar a message
- [x] [Unpin a message](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/unpin-message)
- [x] [React to a message](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/set-reaction)

## User
- [ ] User “me” information
- [ ] User “others” information
- [ ] Search users
- [ ] *User status changes
- [x] [Change my status](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/user-presence)

**Comment by sacOO7** [comment]
One more issue
Identifying type of message from messageObject
1. Text
2. Video
3. Audio
4. File
5. Image
6. Reply
7. Tag
8. Link metadata 
I don't know specific types, but it will be useful, if you can provide with message type details as well as how to parse them from the JSONdata

**Comment by sacOO7** [comment]
API for unsubscribing a room
Stop receiving messages from a room

**Comment by rafaelks** [comment]
@sacOO7 For the message type, until we have something on the Docs, you can use this codes:

- https://github.com/RocketChat/Rocket.Chat.iOS/blob/a768b010d023e3fc72c6dc8e7f31797acb81407e/Rocket.Chat/Models/Message.swift#L60-L71
- https://github.com/RocketChat/Rocket.Chat.iOS/blob/a768b010d023e3fc72c6dc8e7f31797acb81407e/Rocket.Chat/Models/Message.swift#L13-L34
- https://github.com/RocketChat/Rocket.Chat.iOS/blob/a768b010d023e3fc72c6dc8e7f31797acb81407e/Rocket.Chat/Models/Mapping/MessageModelMapping.swift#L14-L70

**Comment by rafaelks** [comment]
@rodrigok Can you describe to us how to stop a subscription from a method? The example @sacOO7 is talking about is to stop receiving updates from messages in a room.

**Comment by sacOO7** [comment]
Any updates on Oauth?

**Comment by MartinSchoeler** [comment]
@rafaelks is this issue still relevant? If it is, is it updated?

**Comment by rafaelks** [comment]
@MartinSchoeler No, we can close it. Thanks.
