### ISSUE TITLE
CentOS Documentation

### ISSUE THREAD

**Issue by e3v** [RocketChat/docs-old#343]
The official installation documentation for CentOS does not produce a working install. It recommends NodeJS 4.5, but Rocket.Chat fails to run with this version. I upgraded my install to 4.8.2 and it ran without issue.

https://rocket.chat/docs/installation/manual-installation/centos

Additionally I recommend using the following command when starting Rocket.Chat to use the specific version that is required instead of the default 6.x.x.

n use 4.8.2 main.js

If there is a better way to set this as the default version of NodeJS, I would recommend that. I am just a new sysadmin though and I am not aware of anything.

**Comment by vcapretz** [comment]
Hi @e3v, as put in #373 I decided to open a PR to make 4.8.4 the recommended Node.js version! the PR is here https://github.com/RocketChat/Rocket.Chat.Docs/pull/376 in case you want to get notifications

**Comment by MartinSchoeler** [comment]
Closed By #376
