### ISSUE TITLE
Create user docs

### ISSUE THREAD

**Issue by docsncode** [RocketChat/docs-old#353]
User docs articles need to be updated and missing articles for new features need to be added.

- [x] Select a server ( #405 )
- [x] Create a Account ( #406 )
- [x] Login (#408)
- [x] Channels: ( https://github.com/RocketChat/Rocket.Chat.Docs/pull/390 )
- [x] Messaging: (#407)
- [x] Channel Actions (Flex-Tab) ( #415 )
- [x] Preferences & Account ( #414 )

**Comment by MartinSchoeler** [comment]
Done!
