### ISSUE TITLE
Mapping Github @mentions to Rocket.Chat direct messages?

### ISSUE THREAD

**Issue by brylie** [RocketChat/docs-old#367]
Our project manager has trouble following all of the activity on GitHub, and sometimes misses when we @mention her username. We would like to make her work easier by direct messaging her on Rocket.Chat when we @mention her username on GitHub.

How can we map GitHub @mentions to our Rocket.Chat instance as direct messages?

**Comment by gdelavald** [comment]
Issue moved to [RocketChat/Rocket.Chat #7856](https://github.com/RocketChat/Rocket.Chat/issues/7856) via [**ZenHub**](https://www.zenhub.com/)
