### ISSUE TITLE
Duplicate Posts

### ISSUE THREAD

**Issue by evok3d** [RocketChat/docs-old#369]
Hi,

When i type into rocket.chat it works perfectly fine, though when i type something into telegram, it goes to rocket.chat and then comes back again into telegram creating a duplicate no matter which user types the message. Is there a way to fix this?

**Comment by MartinSchoeler** [comment]
This issue is not about Rocket.chat please see [guidelines for support](https://rocket.chat/docs/getting-support) for questions about integrations or custom webhooks.
