### ISSUE TITLE
recommended nodejs version

### ISSUE THREAD

**Issue by localguru** [RocketChat/docs-old#373]
Hi,

which is the recommended nodejs version for RocketChat?

There are for example different information. Here v4.7.1 is recommend:

https://rocket.chat/docs/installation/manual-installation/debian 

Here v4.5.0 is recommend:
https://rocket.chat/docs/installation/manual-installation/ubuntu#2-install-rocketchat

Shouldn't it be version 4.8.4 for security reasons?

Ciao!
Marcus

**Comment by vcapretz** [comment]
Probably both of them works just fine, but 4.8.4 should indeed be recommended because of the security reasons, as described here: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V4.md#4.8.4 

can I send a PR for this one @rodrigok?
