### ISSUE TITLE
npm inherits needed?

### ISSUE THREAD

**Issue by localguru** [RocketChat/docs-old#374]
Hi,

on CentOS Installation `npm install -g inherits n` is needed, see https://rocket.chat/docs/installation/manual-installation/centos 

Why not on Ubuntu/Debian?
https://rocket.chat/docs/installation/manual-installation/ubuntu
https://rocket.chat/docs/installation/manual-installation/debian

Ciao!

**Comment by MartinSchoeler** [comment]
@geekgonecrazy do we really need that `Inherits` on the centOS installation?

**Comment by geekgonecrazy** [comment]
eh... I can't see any good reason for it to be needed.  But we've seen people have a lot more trouble on centos then other platforms.  Maybe to do with node.js packaging?  not sure.  So ideally that whole guide should probably be revisited to make sure it still works and try to trim some steps out

**Comment by MartinSchoeler** [comment]
@localguru have you already tried to do only a `npm install` without the `Inherits`?

**Comment by MartinSchoeler** [comment]
Due lack of response i will be closing this issue, if you manage to run `npm install` without `Inherits` please open a new issue asking to be removed from the doc. Thanks!
