### ISSUE TITLE
SSL rewrite problem.

### ISSUE THREAD

**Issue by BetaStacks** [RocketChat/docs-old#378]
I am trying to setup ssl on my apache2 server via the directions provided in the docs. 

When I use:
`RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           ws://localhost:3000/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*)           http://localhost:3000/$1 [P,L]

ProxyPassReverse / http://localhost:3000/` 

My apache server wont start.

**Comment by MartinSchoeler** [comment]
This issue is not related to Rocket.Chat docs.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).
