### ISSUE TITLE
Broken link: How it all started (in README.md of the Rocket.Chat repo)

### ISSUE THREAD

**Issue by SebAlbert** [RocketChat/docs-old#381]
The link "how it all started" from the README.md [in the source repository Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) pointing to http://osdelivers.blackducksoftware.com/2016/06/10/rocket-chat-hosted-chat-services/ is broken: The response seems to replace and then complain about the hostname, it reads:

> Invalid URL
> 
> The requested URL "http://%5bNo%20Host%5d/2016/06/10/rocket-chat-hosted-chat-services/", is invalid.

I initially opened this [on the actual source repository](https://github.com/RocketChat/Rocket.Chat/issues/8169), but was redirected here.

**Comment by vcapretz** [comment]
hey @SebAlbert I just fixed it! https://github.com/RocketChat/Rocket.Chat/pull/8253 the blog changed its URL
