### ISSUE TITLE
rocket.chat-freebsd-develop.tgz not found

### ISSUE THREAD

**Issue by ghost** [RocketChat/docs-old#398]
https://cdn-download.rocket.chat/build/rocket.chat-freebsd-develop.tgz

404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: build/rocket.chat-freebsd-develop.tgz
RequestId: 78AAAB0759FC89C5
HostId: DfxYXPxAKVrwvGD9Z74SaCWyfXxygAs0zX8hzyZcRP82A2zGUoEU5+WcEjYv0/tzCLivDJtoXI8=

Is there an alternative link?

**Comment by MartinSchoeler** [comment]
Hello @scornet could you join us on [this](https://demo.rocket.chat/channel/freebsd-compat) channel on our demo server to further discuss this? Thanks
