### ISSUE TITLE
Realtime API

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/docs-old#402]
Hi,
In docs you write: (https://rocket.chat/docs/developer-guides/realtime-api#realtime-api)

> IMPORTANT! These docs are based on an unreleased version of the API. If you want to try it out, point your client to wss://demo.rocket.chat/websocket.

Is Realtime API ready for production now or still is an experimental feature?

**Comment by cyclops24** [comment]
Anyone knows about Realtime API state?

@karlprieb , @ggazzo , @rodrigok , @engelgabriel , @gdelavald , @MartinSchoeler , @Sing-Li

**Comment by gdelavald** [comment]
Hey, nothing changed with the state of realtime API, it's still an experimental feature.

**Comment by uinz** [comment]
any update or schedule ?

**Comment by mnlbox** [comment]
@gdelavald any news?
