### ISSUE TITLE
Use meteor npm install instead of npm install

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/docs-old#403]
We have lots of places using `npm install` when they should be using the meteor command. 
A example https://github.com/RocketChat/Rocket.Chat.Docs/blame/4922c1ae1c733995fc68cdd46beccfc67d148483/3.%20Installation/4.%20Manual%20Installation/OpenSUSE/README.md#L194

**Comment by localguru** [comment]
Don't understand fully. Which command should it be instead of `npm install`?

**Comment by brooksbecton** [comment]
I'd like to tackle this. 
I just want to make sure I change the right ones 😓 Anything that is installing globally or using `sudo` can probably stay the same right? 

I can get a list of files and locations if it just needs to be reviewed case by case.
