### ISSUE TITLE
Docker Compose link error

### ISSUE THREAD

**Issue by jdoose** [RocketChat/docs-old#41]
Hello eveybody,

in https://rocket.chat/docs/installation/docker-containers/docker-compose is a link to the "Docker Images Available" pointing to https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/content/Deployment/docker%20images%20available.md which does not exist anymore.
The correct target would be:
https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/3.%20Installation/3.%20Docker%20Containers/Available%20Images.md

**Comment by engelgabriel** [comment]
FIXED
