### ISSUE TITLE
[Important] Docs are unavailable in new site

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/docs-old#419]
Hi guys,
Docs are unavailable in new site:
https://rocket.chat/docs/

**Comment by MartinSchoeler** [comment]
@cyclops24 could you check again? Seems to be working for me

**Comment by cardoso** [comment]
Not working here either

**Comment by MartinSchoeler** [comment]
We are making some changes on the website, and we are still setting up some things. Try this url https://docs.rocket.chat/

**Comment by cyclops24** [comment]
It's redirect https://rocket.chat/docs/ to https://docs.rocket.chat/ and fixed now. Thanks 😉
