### ISSUE TITLE
Install / update instructions manual install are broken

### ISSUE THREAD

**Issue by alexroosenstein** [RocketChat/docs-old#420]
It's concerns the following section:
https://docs.rocket.chat/installation/manual-installation/ubuntu/#install

The latest stable download link (https://rocket.chat/releases/latest/download) is broken, it returns a 404.

**Comment by georg94** [comment]
Obviously teh rocket.chat domain is redirecting to github now (since today?). Anyways if you use old.rocket.chat you can download the release (we have the same issue at the moment)
https://cdn-download.rocket.chat/build/rocket.chat-0.58.4.tgz?(https://old.rocket.chat/releases/latest/download)

**Comment by MartinSchoeler** [comment]
Should be working by now. Please reopen if this issue happens again. Thanks!
