### ISSUE TITLE
Update permission directory and add why certain permissions are set by default

### ISSUE THREAD

**Issue by xenithorb** [RocketChat/docs-old#43]
Please update the permissions directory to reflect what is currently present on the rocket.chat codebase.

https://rocket.chat/docs/administrator-guides/permissions/

**Comment by MartinSchoeler** [comment]
Moved to the [Documentation Map](https://github.com/RocketChat/docs/blob/master/contributing/documentation/documentation-map/README.md)

https://github.com/RocketChat/docs/tree/master/contributing/documentation/missing-and-outdated-list#permissions
