### ISSUE TITLE
Vagrantfile in the documentation does not work

### ISSUE THREAD

**Issue by nacho-marin** [RocketChat/docs-old#433]
The Vagrantfile reflected at https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/3.%20Installation/5.%20Automation%20Tools/Vagrant/README.md does not work: some scripts seem to be missing.

You can find the output generated after executing vagrant up [here](https://www.dropbox.com/s/70kuhctc2s8uqkj/rocketchat-server-vagrant.txt?dl=0)

Environment:

$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0

$ vagrant -v
Vagrant 2.0.0

$ vboxmanage --version
5.1.28r117968

**Comment by nacho-marin** [comment]
Btw, I removed the first three lines and the last one in README.md to have a valid Vagrantfile

**Comment by MartinSchoeler** [comment]
@nacho-marin did you make the proper changes on the vagrant file? Like changing the `http://your_hostname.com` to your hostname?

**Comment by MartinSchoeler** [comment]
Cant determine if it is a problem with the script or if it was missing information required by the user. Closing this. If the problem happens again please open a new issue with updated details. Thanks!
