### ISSUE TITLE
Auto SSL with AWS

### ISSUE THREAD

**Issue by dstepp** [RocketChat/docs-old#437]
Rocket.Chat.Docs/3. Installation/4. Manual Installation/Ubuntu/Snaps/AutoSSL.md

Running on Ubuntu 16.04 hosted on AWS EC2 with my domain registered with Route 53. 

Following these instructions and I get RocketChat up and running when using http://192.168.1.1:8080 but it won't work with my-domain.com, http://my-domain.com, or any of the others. 

Researching, it looks like I need to add https://caddyserver.com/docs/tls.dns.route53 this to my configuration. Could you update the instructions with how to do this? Thank you!

**Comment by 707eric** [comment]
I had a similar issue with Caddy.  What worked for me was

Make sure Caddyfile looks similar to:

YOURDOMAIN.com
proxy / localhost:3000 {
  websocket
  transparent
}

In /etc/hosts
add your public IP and the FQDN you used in your Caddyfile

Then do
cd /var/snap/rocketchat-server/1188       (im not sure if the folder number (1188) changes so your exact path might me different)
Then
sudo /usr/bin/snap run rocketchat-server.rocketchat-caddy

You should see Caddy start and run without any errors and require you hitting Cntrl+C to make it stop.

**Comment by dstepp** [comment]
Thanks! I got it working via Nginx today. I'm going to test my fix with Caddy this weekend and will post my updates to the documentation. I think it was a goofy firewall rule on my server that messed it up. (I was using AWS Ubuntun 16.04 AMI)

**Comment by MartinSchoeler** [comment]
@dstepp @707eric Great to hear that you get it working! Are you guys interested in creating a pull request with that fix? Thanks!

**Comment by Rodriq** [comment]
Auto SSL with snaps docs https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/snaps/auto-ssl-with-snaps
