### ISSUE TITLE
What is the official way to do your own build of the mobile apps? [Broken link]

### ISSUE THREAD

**Issue by leolara** [RocketChat/docs-old#44]
Here:

https://github.com/RocketChat/Rocket.Chat.Docs/blame/master/5.%20Developer%20Guides/6.%20Mobile%20Apps/README.md#L13

there is a broken link to the official way of building mobiles apps. I am very interested in this. Is this done in the standard way for meteor-cordova apps? Like explained here: https://guide.meteor.com/mobile.html#introduction

**Comment by engelgabriel** [comment]
Hi @leolara 

We have not used the meteor way of building apps, because we wanted our app to connect to many backend server.

Thats why we created our own Cordova app from scratch.

Best,

Gab

**Comment by leolara** [comment]
@engelgabriel If I make my own version of your cordova mobile app to only connect to my own server always and change the branding, will I have problem with the App Store saying that my app does not differ from the website and that people should use the website without the need for an app?

**Comment by geekgonecrazy** [comment]
@leolara ours doesn't have issue with this, along with many other cordova apps currently in the app store.  I think Apple's is a bit more work, since you do have to create an account for them to log on and use the app before they approve it.
