### ISSUE TITLE
Image links on develop guides being malformed

### ISSUE THREAD

**Issue by vncdias** [RocketChat/docs-old#447]
Some of the links generated on docs are malformed, resulting on broken images
They're missing the domain (docs.rocket.chat).

![image](https://user-images.githubusercontent.com/5617948/32284533-4ce7d628-bf06-11e7-8940-d20eff8ca93a.png)

**Comment by geekgonecrazy** [comment]
I think these are all fixed.  Please open an issue if you see any specific ones broken

**Comment by vncdias** [comment]
tks @geekgonecrazy!
