### ISSUE TITLE
Missing docs for "users.register" REST API

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/docs-old#452]
https://github.com/RocketChat/Rocket.Chat/blob/8fd7eb427ba34d090cf5abee03f4500c63878efe/packages/rocketchat-api/server/v1/users.js#L138-L158

**Comment by MarcosSpessatto** [comment]
Please, @rafaelks they are here: #282, and [here](https://github.com/RocketChat/docs/blob/master/developer-guides/rest-api/users/register/README.md).
