### ISSUE TITLE
Edge support?

### ISSUE THREAD

**Issue by fabiopolimeni** [RocketChat/docs-old#453]
On this doc [page](https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/4.%20User%20Guides/Voice%20and%20Video%20Calls/README.md), you say Edge doesn't support WebRTC, and therefore voice and video capabilities might no work on Rocket.Chat. This is a 2 years old statement, today WebRTC is supported on Edge, despite it is not advertised on the main WebRTC page (examples work though). I don't have a quick way to test Rocket.Chat video features, but if anyone does, it would be nice to have the documentation updated.

**Comment by geekgonecrazy** [comment]
Please feel free to open a PR to remove that statement.  :smile:

**Comment by vchrombie** [comment]
Can I take this issue so that I can start working and get started?

**Comment by geekgonecrazy** [comment]
if you would like to contribute please do.  :+1:

**Comment by Dalben96** [comment]
The link in the issue dosen't work.
I belive the new link would be https://rocket.chat/docs/user-guides/voice-and-video-calls/
