### ISSUE TITLE
Broken links at the welcome screen

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/docs-old#475]
The links are missing the /docs/ on here https://rocket.chat/docs/

**Comment by docsncode** [comment]
Prepend the links with `{{ site.url}}` to have Jekyll add the correct base URL for the environment e.g on localhost nothing will be added on production `/docs` will be added. Example of full usage:

`<a href="{{ site.url }}/contributing/">Contributing</a>` include a forward slash at the beginning.
