### ISSUE TITLE
Why Ubuntu 14.04 instead 16.04

### ISSUE THREAD

**Issue by edpittol** [RocketChat/docs-old#479]
In the installation docs has the recommendation to install the Rocket.Chat over the Ubuntu Server 14.04 LTS. Has some restriction to run the application over the Ubuntu Server 16.04 LTS?

**Comment by geekgonecrazy** [comment]
Just needs updated.  Feel free to open a PR to update it.  :)

**Comment by localguru** [comment]
Yes, 16.04 LTS is fine, no problem here
