### ISSUE TITLE
Canonical tag is duplicating /docs

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/docs-old#482]
```
<link rel="canonical" href="https://rocket.chat/docs/docs/contributing/">
```

**Comment by geekgonecrazy** [comment]
Looks like absolute_url is what is doing it: https://jekyllrb.com/docs/templates/  it combines baseurl which I assume is rocket.chat/docs with page.url which I assume is /docs/contributing/

**Comment by engelgabriel** [comment]
@MartinSchoeler this needs to be fix urgently, otherwise Google will penalise us on the search results.

**Comment by MartinSchoeler** [comment]
Fixed!
