### ISSUE TITLE
Document stream-notify-logged

### ISSUE THREAD

**Issue by cardoso** [RocketChat/docs-old#491]
We use stream-notify-logged in iOS to subscribe to permissions-changed events, but in the docs there's no stream-notify-logged and permissions-changed is in stream-notify-all.

https://rocket.chat/docs/developer-guides/realtime-api/subscriptions/stream-notify-all/

Is stream-notify-all deprecated? Can we add stream-notify-logged to the docs?

**Comment by docsncode** [comment]
@cardoso thank you for pointing this out. Do you know who's responsibility this area falls under (API or permissions-changed events or the specific event)?

**Comment by MartinSchoeler** [comment]
Closed by https://github.com/RocketChat/docs/pull/832

**Comment by cardoso** [comment]
Thanks @MartinSchoeler :+1:
