### ISSUE TITLE
How can add iframe code in our website

### ISSUE THREAD

**Issue by anujdhimanjava** [RocketChat/docs-old#496]
As i have read your documentation  for i frame automatically login i follow these steps :-1: 

 1. Go to Adminstration > Accounts > Iframe and enable it. 
 2. Hit rest api and got userId and authToken . 
 But from where i got iframe code and how can i integrate it with application . As u mention  use it  Meteor.loginWithToken('3wzsXzG53AN5qU_byQVZZNt79oh5wviOMpwB2IHOyHR', callback);
I got this error : 
Uncaught ReferenceError: Meteor is not defined
and where i define rocket server url . Please help me how can i login in rocket chat automatically when login in our application using iframe

**Comment by MartinSchoeler** [comment]
This seems more like a support question than an issue.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
