### ISSUE TITLE
Deep linking format

### ISSUE THREAD

**Issue by cardoso** [RocketChat/docs-old#497]
Referencing: https://github.com/RocketChat/Rocket.Chat.iOS/issues/440

We need to discuss and document our deep linking format so we can be consistent across all platforms.

Also, discuss which parameters to support so we can have nice deep-link features 🙂

**Comment by vchrombie** [comment]
I am really interested in contributing to Rocket.Chat.
Can you help in getting started?

Can I take this issue and start working on it?

**Comment by docsncode** [comment]
@vchrombie are you familiar with our deep linking format? We may need input from the core developers on this topic but if you aren't familiar we'd still love to have you contribute to the docs. 

Have you seen our [docs contribution guide](https://rocket.chat/docs/contributing/documentation/) and [list of missing/outdated articles](https://rocket.chat/docs/contributing/documentation/missing-and-outdated-list/)? 

Pick a topic you are familiar with from the list, create an issue if there isn't one and start a PR to address it. Please mention me in your issue and PR if you need any assistance.

**Comment by docsncode** [comment]
@cardoso could you or someone familiar with our deep linking create a PR with draft documentation explaining it?
