### ISSUE TITLE
Improve delete message docs

### ISSUE THREAD

**Issue by cardoso** [RocketChat/docs-old#501]
https://rocket.chat/docs/developer-guides/realtime-api/method-calls/delete-message/#delete-message

It needs to talk about the force-delete-message permission and the Message_ShowDeletedStatus setting

"As mentioned in requirements, you must be logged in to be able to delete a message along with having the permission delete-message."

This is wrong. You don't need delete-message to be able to delete. delete-message allows deletion of any message, but still respects Message_AllowDeleting_BlockDeleteInMinutes unlike force-delete-message which bypasses everything.

**Comment by docsncode** [comment]
@cardoso could you provide a draft PR with technical details and we will finish it off?
