### ISSUE TITLE
Move Docs for new rooms.get / subscriptions.get etc

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/docs-old#512]
https://github.com/RocketChat/Rocket.Chat/pull/8947

This should be very easy the documentation is already on the PR.

**Comment by docsncode** [comment]
@rodrigok could you create a PR for your work's documentation?

**Comment by xbolshe** [comment]
rooms.* are done: [PR #590](https://github.com/RocketChat/docs/pull/590) and [rooms](https://rocket.chat/docs/developer-guides/rest-api/rooms/)
