### ISSUE TITLE
Meteor OAuth Provider configuration is missing

### ISSUE THREAD

**Issue by openp2pdesign** [RocketChat/docs-old#514]
On the **OAuth Provider Configuration** page, [the Meteor section](https://github.com/RocketChat/docs/blob/master/administrator-guides/authentication/oauth/README.md#meteor) is empty with just a _TBD_.

This would help users in integrating Rocket.chat with Meteor app, see also #72 and #460.

**Comment by docsncode** [comment]
@openp2pdesign I will make sure this is worked on. To simplify managing the process, I will close this duplicate issue and ask the core team to assist us with creating example code for #460 and then complete #72.
