### ISSUE TITLE
Add documentation about Livechat OmniChannel

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/docs-old#518]
Describe also an additional step on Facebook Pages manager:

* Open Facebook page settings
* Goto Messenger Platform -> Subscribed Apps
* Assign Primary Receiver role to  "Rocket.Chat"

**Comment by docsncode** [comment]
@sampaiodiego Is this something you worked on?

**Comment by sampaiodiego** [comment]
yes it is: https://github.com/RocketChat/Rocket.Chat/pull/8807

**Comment by tostanoski** [comment]
Here's a quick how-to on setting this up. It likely needs work, but it's a start.
[omni.txt](https://github.com/RocketChat/docs/files/2220480/omni.txt)

**Comment by Faria1212** [comment]
Documentation developed! https://docs.rocket.chat/guides/omnichannel-guides
