### ISSUE TITLE
Improve styles for headers, code boxes and spacing for paragraphs

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/docs-old#541]
Let's keep to Semantic-UI and use the definitions from:

https://semantic-ui.com/globals/site.html

**Comment by docsncode** [comment]
@engelgabriel ideally we can share a typography style across the website and docs. Would you like Significa to standardise the website around Semantic UI too?

**Comment by engelgabriel** [comment]
Yes, I'd like Significa to standardise the website around Semantic UI too.
