### ISSUE TITLE
Sync HEADER and FOOTER with the website

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/docs-old#542]
Ideally we should be able to just copy the included template form one to the other.

**Comment by docsncode** [comment]
@MartinSchoeler I will take this one and standardise any shared components and scss. I will look into using a git sub module.

**Comment by MartinSchoeler** [comment]
Closed by https://github.com/RocketChat/docs/commit/77f2351a1c384fff3aa34d2eec9ef945e5470701
