### ISSUE TITLE
Add instructions to the contribution guides on how to link a WIP PR to an issue 

### ISSUE THREAD

**Issue by docsncode** [RocketChat/docs-old#548]
It would be useful to potential contributors (internal or external) to see if an issue is currently being worked on by someone.

Could you please add instructions to the docs contribution guide on how to link an issue with a WIP PR.

**Comment by timkinnane** [comment]
@MartinSchoeler I was about to make an issue for basically this, then noticed your recent updates.

I followed the link to [Developer Guides](https://rocket.chat/docs/developer-guides/) but I think for external contributors it's hard to tell that the 'branches-and-releases' page is where you should go for information on submitting a PR. It also has a lot of information that is only relevant to the internal team - e.g. mentions assigning yourself to an issue, which they can't do.

I would like to see under [docs/contributing/developing/README.md](https://github.com/RocketChat/docs/blob/master/contributing/developing/README.md) basic instructions for community contributors, on the process of making a contribution. Something like:

1. Find or create an issue
Follow the issue template instructions to make sure the core team understands your intentions.
We won't accept PRs without an issue created first, for context to review the submission.

2. ...whatever the actual process should be for forking, feature/hotfix branches, code style, CI etc.

The main readme should also link here, so there's not multiple versions of the process.
https://github.com/RocketChat/Rocket.Chat#how-to-contribute

Or possibly put all this information in a `CONTRIBUTING.md` in the repo and link directly to that. That could then become boilerplate and allow changes for repos if they have more specific processes.

You could draw some boilerplate content from the [opensource.guide](https://github.com/github/opensource.guide/blob/gh-pages/CONTRIBUTING.md).
