### ISSUE TITLE
Can't succsessfully set a Webhook in Telegram

### ISSUE THREAD

**Issue by vongomben** [RocketChat/docs-old#56]
hi.
I'm following [this](https://github.com/RocketChat/Rocket.Chat.Docs/blob/6bb9cd6568e6a0e3a64467dfc8bfd4d0395121e7/5.%20Administrator%20Guides/Integrations/Telegram.md) guide but get somehow redirected to 'https://core.telegram.org' instead of receiving an error message (or a positive one).

The rocket chat documentation [dates back to april 6](https://github.com/RocketChat/Rocket.Chat.Docs/commit/b725aae95fe196c8c4b4dbc0aa92c3dbd488a747) ([the very date of major Telegram bot 2.0 APIs were release](https://core.telegram.org/bots/2-0-intro)) and have been pdated by @marceloschmidt. I wonder if [the 2.1 update](https://core.telegram.org/bots/api#recent-changes) broke somehow the process. 

Do you have Rocket>Telegram bot working?

Thanks in advance for any help

**Comment by vchrombie** [comment]
Can I get started by taking this issue and working on it?

**Comment by MartinSchoeler** [comment]
@vchrombie Of course! We are happy to accept Pull Requests. Thanks!

**Comment by MartinSchoeler** [comment]
Actually seems that the telegram integration documentation hast been updated after this issue. Please test it again and create a new issue if the problem persists. Thanks!
