### ISSUE TITLE
Improve permissions documentation

### ISSUE THREAD

**Issue by jcatarino** [RocketChat/docs-old#564]
It would be useful for people that administer servers to have this kind of information:

- Explain what are global scope and channel scope roles.
- Finalise describing all permissions in the documentation.
- Why do user created roles don't appear in contact sidebar like "Admin" and "Owner" ?
- What are the default settings for the permissions ?

Thank you.

**Comment by MartinSchoeler** [comment]
Moved to the [Documentation Map](https://github.com/RocketChat/docs/blob/master/contributing/documentation/documentation-map/README.md)

https://github.com/RocketChat/docs/tree/master/contributing/documentation/missing-and-outdated-list#permissions
