### ISSUE TITLE
unreads

### ISSUE THREAD

**Issue by Leeerjin** [RocketChat/docs-old#565]
/api/v1/im.history?roomId=m9N72ArGFKvxF7vqssG4kvetZjqqegsqGZ&inclusive=true&unreads=true

'unreadNotLoaded' always returns 0

This is true even if there are unread messages.

**Comment by MartinSchoeler** [comment]
@Leeerjin This looks more like a bug than a documentation issue. Please reopen this on the main repository. Thanks!
