### ISSUE TITLE
How to build Rocketchat on ubuntu 14.04 ?

### ISSUE THREAD

**Issue by amadou009** [RocketChat/docs-old#57]
Hello, I had install  Rocketchat via  this url : https://medium.com/@unnikked/how-to-install-rocket-chat-on-ubuntu-14-04-999673bfcfb7#.kwx3f02j6. When I launch " meteor build " nothing happen.
It downloads but nothing.
![capture d ecran de 2016-07-26 12 25 29](https://cloud.githubusercontent.com/assets/18334094/17152335/2bed8fa4-532c-11e6-92fe-f2fc5e4c4594.png).
Someone can help me ?

**Comment by engelgabriel** [comment]
If you just want to run Rocket.Chat, please follow https://rocket.chat/docs/installation/manual-installation/ubuntu/

If you are trying to develop and build a new version, please be aware that the initial download of Meteor, it can take a long time indeed.
