### ISSUE TITLE
Imoprove Menu and Table of contents

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/docs-old#598]
Main improvements:

- [ ] Clickable ToC with H1s 
- [ ] Float as you scroll the page
- [ ] Expandable and collapsible 

Good examples:

https://gluu.org/docs/ce/3.1.2/installation-guide/
https://semantic-ui.com/collections/message.html

**Comment by MartinSchoeler** [comment]
<img width="735" alt="screen shot 2018-02-22 at 10 11 57 am" src="https://user-images.githubusercontent.com/20868078/36540382-dcef830a-17b8-11e8-9cbb-6fa23369593e.png">
