### ISSUE TITLE
Verification Emails not Being Sent - Docker

### ISSUE THREAD

**Issue by rogueslerv21** [RocketChat/docs-old#659]
Verification emails are not being sent to users. Setup according to the documentation here [https://rocket.chat/docs/installation/docker-containers/](url) thus my compose file did not have a MAIL_URL variable set:
`rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://chat.inumio.com
    - Accounts_UseDNSDomainCheck=True
  links:
    - db:db
  ports:
    - 3000:3000
`

After noticing this was not working, I found some references to adding the var and configured it as such:
`MAIL_URL=smtp://USER@gmail.com:PASS@gmail.com:587/`

In the Admin GUI, SMTP is defined using the same user, pass and port to gmail and admin initiated registrations and invitations are delivered fine and always were, prior to the MAIL_URL being set. Any advice on this?

`Rocket.Chat Version: 0.62.2`
`NodeJS Version: 8.9.3 - x64 `

**Comment by MartinSchoeler** [comment]
@rogueslerv21 Good to know that you managed to get it working! Do you want to create a pull request fixing this doc? Thanks!

**Comment by rogueslerv21** [comment]
@MartinSchoeler Sorry if I misspoke but verification emails are not being sent while admin initiated invitations and registrations are sending. But I found other references stating to add the MAIL_URL var so I did that without any effect.

In Accounts > Registration > 'Email Verification' is set to true
And in Email > SMTP > Verification > 'Custom' is set to false
