### ISSUE TITLE
Payload of rooms save notification POST

### ISSUE THREAD

**Issue by artur-ios-dev** [RocketChat/docs-old#692]
https://rocket.chat/docs/developer-guides/rest-api/rooms/savenotification/#rooms-save-notification-post

In example payload there is a argument called `desktopNotifications` which is not listed in Payload argument's list. Is this one indeed needed (if so need to document it in argument's list), otherwise let's remove it from the example.

**Comment by MartinSchoeler** [comment]
@MarcosSpessatto Can you take a look at this one?
