### ISSUE TITLE
/api/v1/me needs better documentation for the preferences

### ISSUE THREAD

**Issue by cardoso** [RocketChat/docs-old#695]
https://rocket.chat/docs/developer-guides/rest-api/authentication/me/

There are a number of preferences shown in the example result, but these are the only ones I receive:

```javascript
{
    "sidebarViewMode": "condensed"
    "sidebarShowUnread": true
    "sidebarHideAvatar": false
    "sidebarShowFavorites": true
}
```

Problems:

1. None of these are in the example.
2. There is no description of what they do.

Possible solutions:

1. Include these in the example. 
 - Explain why all the others may not come in the result. 
 - If they should never come, then remove them from the example)
2. Describe what each preference does (maybe in a separate doc)

**Comment by MartinSchoeler** [comment]
I believe that only preferences that has been changed appear in this list, since this is default behavior in Rocket.Chat, i could be wrong @MarcosSpessatto any ideas?

**Comment by MarcosSpessatto** [comment]
Yes @MartinSchoeler, you're right, only preferences that has been changed appear in this list, this is the behaviour on backend. If you don't changed the preferences yet, then the list should be empty, because they're not save on db.

**Comment by MarcosSpessatto** [comment]
Closed by https://github.com/RocketChat/docs/pull/728
