### ISSUE TITLE
api/v1/channel.list does not return list usernames

### ISSUE THREAD

**Issue by PabloBaamonde** [RocketChat/docs-old#748]
api / v1 / channel.list does not return list usernames, previously in other versions if you return this parameter.

Tembia has changed channel.list.joine and channel.info, which also returned the usernames parameter. Currently it returns a username parameter, but it is not a list, it is a string.

How can I get the list of users of a channel?

**Comment by MartinSchoeler** [comment]
@PabloBaamonde You can use the channels.members endpoint https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/channels.js#L498

This is currently not documented

**Comment by PabloBaamonde** [comment]
@MartinSchoeler  thanks
