### ISSUE TITLE
Raspbian read only file system

### ISSUE THREAD

**Issue by Miracle916** [RocketChat/docs-old#767]
I have an issue with a directory /snap/rocketchat-server/programs/server when I tried to change the permissions it says is a read only file system. I tried as sudo too and nothing change, still as a read only file.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
