### ISSUE TITLE
Add livechat and bots documentation

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/docs-old#779]
The Hubot adapter repo often receives new issues asking about what's possible with using a bot as a livechat agent and how to set that up. It's not really the appropriate domain for the adapter, but there's no where else to go. We need someone who understands it in detail to setup a document either under the bots section or the livechat administrator guides, that covers this approach.

Related #518 and adapter issues [195](https://github.com/RocketChat/hubot-rocketchat/issues/195) and [277](https://github.com/RocketChat/hubot-rocketchat/issues/277)

**Comment by Faria1212** [comment]
https://docs.rocket.chat/guides/omnichannel-guides
