### ISSUE TITLE
docs.rocket.chat not working

### ISSUE THREAD

**Issue by mikaelmello** [RocketChat/docs-old#788]
Domain is not responding

**Comment by MartinSchoeler** [comment]
It seems to be working fine now, it could be rebuilding from a merge when you accessed. Thanks!

**Comment by mikaelmello** [comment]
@MartinSchoeler Just checked, that domain is still not working, `rocket.chat/docs` works though

```
$ nslookup docs.rocket.chat
Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
Name:	docs.rocket.chat
Address: 45.55.199.111
```

Not working on Chrome from both PC and Android and Firefox from PC, connection just times out.
