### ISSUE TITLE
Keycloak Integration

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/docs-old#790]
Keycloak is an custom OAuth provider: openID protocol

https://www.keycloak.org/

We need to write the documentation based on the discussions from the following issues:

https://github.com/RocketChat/Rocket.Chat/issues/3897
https://github.com/RocketChat/Rocket.Chat/issues/7418
https://github.com/RocketChat/Rocket.Chat/issues/10845

**Comment by saplla** [comment]
We've automated the configuration of KeyCloak in our Helm chart using the following env vars:
```
    Accounts_OAuth_Custom-Keycloak: true
    Accounts_OAuth_Custom-Keycloak-url: https://auth.mycorp.com/auth
    Accounts_OAuth_Custom-Keycloak-token_path: /realms/mycorp/protocol/openid-connect/token
    Accounts_OAuth_Custom-Keycloak-token_sent_via: Header
    Accounts_OAuth_Custom-Keycloak-identity_token_sent_via: header
    Accounts_OAuth_Custom-Keycloak-identity_path: /realms/mycorp/protocol/openid-connect/userinfo
    Accounts_OAuth_Custom-Keycloak-authorize_path: /realms/mycorp/protocol/openid-connect/auth
    Accounts_OAuth_Custom-Keycloak-scope: openid
    Accounts_OAuth_Custom-Keycloak-id: rocketchat
    Accounts_OAuth_Custom-Keycloak-login_style: redirect
    Accounts_OAuth_Custom-Keycloak-button_label_text: Login via Keycloak
    Accounts_OAuth_Custom-Keycloak-button_label_color: "#FFFFFF"
    Accounts_OAuth_Custom-Keycloak-button_color: "#13679A"
    Accounts_OAuth_Custom-Keycloak-username_field: preferred_username
    Accounts_OAuth_Custom-Keycloak-merge_users: false
```
We pull `Accounts_OAuth_Custom-Keycloak-secret` from a secret.

One issue is that after installing Rocketchat with helm, someone needs to manually create a new custom OAuth provider called `Keycloak`. As soon as it's created Rocketchat populates it with all of the above values.

It'd be more convenient if Rocketchat scanned the available env vars and then created a `Keycloak` custom OAuth provider automatically to avoid that manual step.

**Comment by NameTheJew** [comment]
Keycloak can also use SAML,
So documentation on integrating both SAML or OAuth would be very useful.
Current rocketchat documentation on SAML isnt very helpful when configuring keycloak, as field names dont match, making it difficult to know what to put where.
https://rocket.chat/docs/administrator-guides/authentication/saml/

Listing pro & cons of authentication methods would also be helpful.

**Comment by mannp** [comment]
> Keycloak is an custom OAuth provider: openID protocol

Hi @engelgabriel I wondered if there was any progress on documenting this at all, as I am passing between threads on github without much success.

**Comment by col-panic** [comment]
I have added some more documentation via https://github.com/RocketChat/docs/pull/1398 - but I would really like to see the issue mentioned by @saplla tackled

> One issue is that after installing Rocketchat with helm, someone needs to manually create a new custom OAuth provider called Keycloak. As soon as it's created Rocketchat populates it with all of the above values.

**Comment by col-panic** [comment]
The resp. bug is documented here https://github.com/RocketChat/Rocket.Chat/issues/10420

**Comment by mbassiouny33** [comment]
Hello,

I'm running Rocket chat with Docker and running a Keycloak server in another container.

I was wondering if there's a way to programmatically configure Oauth instead of having to visit the interface.

I have checked this page : https://rocket.chat/docs/administrator-guides/authentication/oauth/keycloak/

But it only gives instructions via the Web interface.

I can create the client on Keycloak and retrieve the secret programmatically, but is there a any way I can pass it to Rocket.chat via config files, env. variables or even insert in/ modify the Database in order to automate the process?

**Comment by patlachance** [comment]
> We've automated the configuration of KeyCloak in our Helm chart using the following env vars:
> :::
> We pull `Accounts_OAuth_Custom-Keycloak-secret` from a secret.

@saplla do you mind sharing your full chart? I couldn't find changes in https://github.com/saplla/charts/tree/master/stable/rocketchat

**Comment by col-panic** [comment]
I also started some Keycloak SAML documentation in https://github.com/RocketChat/docs/pull/1525

**Comment by ShellyXueHan** [comment]
@engelgabriel Looks like there are screenshots missing in the last part? https://github.com/RocketChat/docs/blob/master/guides/administrator-guides/authentication/oauth/keycloak.md#mapping-non-federated-keycloak-user-roles-to-rocketchat-roles
