### ISSUE TITLE
Deploying Rocket.Chat on Google Compute Engine Doc Error on Browser version

### ISSUE THREAD

**Issue by andrealmar** [RocketChat/docs-old#807]
<img width="712" alt="screen shot 2018-06-21 at 11 11 11" src="https://user-images.githubusercontent.com/537826/41724404-d9839fce-7543-11e8-9e6a-0b8f4c578cb8.png">

It doesn't show the COMPLETE docker command, it only shows: 

`sudo docker run --name rocketchat -p 80:3000 --env ROOT_URL=https://www.test.com `

But if you go to GitHub it shows the complete command:

<img width="988" alt="screen shot 2018-06-21 at 11 12 20" src="https://user-images.githubusercontent.com/537826/41724469-fc8c06be-7543-11e8-8e2f-9d370c9cc52c.png">

`sudo docker run --name rocketchat -p 80:3000 --env ROOT_URL=https://www.test.com --env MONGO_URL=mongodb://db/rocketchat --link db -d rocketchat/rocket.chat`

**Comment by Rodriq** [comment]
A Rocket.Chat App will be set up for the Google Marketplace soon. But using the [docker deployment guide](https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose), you can do a manual install
