### ISSUE TITLE
Add documentation for missing Spotlight endpoint

### ISSUE THREAD

**Issue by Galatoni** [RocketChat/docs-old#819]
Add missing documentation for realtime API endpoint for spotlight searches.

I'm assuming the parameter requirements will be the same for this as it is the Restful API endpoint?

**Comment by shubhangibharti** [comment]
Hi maintainers,

I am a GSoD applicant, have read your ideas list and working on closing tickets present in the list.

I have participated in multiple SoC/WoC and have been involved w/ open source. I have worked with Rest APIs, mobile and software development for chat applications and the project of Application Programming Interfaces (APIs) Documentation seems like a right fit for me.

Can this issue be assigned to me?
