### ISSUE TITLE
FreeBSD installation doc works no more

### ISSUE THREAD

**Issue by bobrof** [RocketChat/docs-old#82]
I have FreeBSD 10.3 x64 installation which is clean enough (no node.js or npm installed). Within newly created jail a rocket.chat installation is made step by step according to manual FreeBSD 10.3 installation document. Everything is built succesfully, but the last 'meteor' command fails with a number of version restriction issues (please see [rocket.txt](https://github.com/RocketChat/Rocket.Chat.Docs/files/465008/rocket.txt) ).
I'm not sure if this is documentation or installation issue, but something is broken here.

**Comment by MartinSchoeler** [comment]
I think it could be related to the fact that this script is using `npm install` instead of `meteor npm install`

**Comment by MartinSchoeler** [comment]
Try using `meteor npm install` instead of `npm install` if the problem persists please open a new issue
