### ISSUE TITLE
Rocketchat Video Conference Call

### ISSUE THREAD

**Issue by Alucard616** [RocketChat/docs-old#824]
Our Company was using Skype for a very long time and we switched to Rocketchat to have a inhouse chat and conference system.
It would be very nice for us, if the Video Conference emplementation (https://rocket.chat/docs/user-guides/voice-and-video-calls/) would be stable so we can completely switch to RC.

**Comment by MartinSchoeler** [comment]
@Alucard616 It seems that you are asking for better stability on the jitsi integration, so this should be posted in https://github.com/RocketChat/Rocket.Chat . Also this pr improves our current documentation on video conferencing https://github.com/RocketChat/docs/pull/841. Thanks!
