### ISSUE TITLE
Add Helm chart

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/docs-old#825]
This would go along side openshift, ansible, and the other automation tools

https://github.com/kubernetes/charts/tree/master/stable/rocketchat

Can be installed via: 
```
helm install stable/rocketchat
```

More info about helm charts here: https://helm.sh/

**Comment by kfirfer** [comment]
Helm chart stable repository is deprecated
Better create dedicate helm chart repository for Rocket
