### ISSUE TITLE
Error: Missing binary. See message above.

### ISSUE THREAD

**Issue by benmaxlevy** [RocketChat/docs-old#837]
When I run main.js, I get this error: Error: Missing binary. See message above. The message "above" is:  
```
##There is an issue with `node-fibers` ##
`/opt/Rocket.Chat/programs/server/node_modules/fibers/bin/linux-x64-64/fibers.node` is missing.
```

Thanks.

**Comment by MartinSchoeler** [comment]
This issue is not related to Rocket.Chat docs.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).

**Comment by Blakskyben** [comment]
fuck
