### ISSUE TITLE
Top menu not highlighted

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/docs-old#861]
When you are in docs you see:

![image](https://user-images.githubusercontent.com/1000217/43405785-050bee50-93f1-11e8-881e-0aaf5ffb222e.png)

It should be like the other pages of the website:

![image](https://user-images.githubusercontent.com/1000217/43405818-1b5f5610-93f1-11e8-8b71-986016d7604f.png)

**Comment by MartinSchoeler** [comment]
Closed in #862
