### ISSUE TITLE
Users.list API endpoint needs corrections

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/docs-old#870]
Something has changed in core and the users.list API endpoint no longer returns any users without adding specific query params. In docs the query is marked as optional. I'm not sure if the docs need updating or the endpoint needs a regression.

**Comment by MarcosSpessatto** [comment]
Hey @timkinnane, I did some tests with the test case you showed, and it's working normally, I was not able to simulate the error, but I remembered that [I had done a PR that dealt with a similar case](https://github.com/RocketChat/Rocket.Chat/pull/11657), so I tested without the fix done in the PR locally, to see if that was the problem, and it really was. Apparently it was fixed, let me know if the problem has not been resolved.
