### ISSUE TITLE
list of setting_id's

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/docs-old#871]
hi guys,
Based on https://rocket.chat/docs/administrator-guides/settings-via-env-vars/ we can set setting's value with environment variables but we need a list of available setting_id's to use this.
I think it's better to refer setting_id's list if it's available to above doc or add this list to it.

**Comment by mnlbox** [comment]
@MartinSchoeler Any news?

**Comment by engelgabriel** [comment]
This can be added by packages, so keeping a full list would be hard. Probably the best thing to do would be to have an interface on the ADMIN panel listing all the available options.\

In the meantime, you can look at the IDs of the Documents in the Setting Collection on the database.

**Comment by mnlbox** [comment]
@engelgabriel Thanks for your reply. Are you any plan to add this in admin panel?

**Comment by reetp** [comment]
Can I bump this please.

We get lots of requests for various environment settings which can never be found.

A list of Env variables is really important.

**Comment by horvan** [comment]
++

**Comment by col-panic** [comment]
The documentation https://rocket.chat/docs/administrator-guides/settings-via-env-vars/  says that i need to know the type of the setting like string, boolean, etc. Why? It is not mentioned on how to get and use this information.

**Comment by ChristySujitha** [comment]
Updated the doc with additional setting parameters: https://docs.rocket.chat/guides/administration/advanced-admin-settings/settings-via-env-vars
