### ISSUE TITLE
Set announcement rest api endpoint missing for groups

### ISSUE THREAD

**Issue by williamoverton** [RocketChat/docs-old#878]
Although an announcement can be set via the UI, it can not be done via the REST API for private groups.

Version	0.65.1
Database Migration	121

(Also, setAnnouncment is not linked for channels in the docs page)

**Comment by MarcosSpessatto** [comment]
@mrminecart can you please open an issue in the [Rocket.chat repo](https://github.com/RocketChat/Rocket.Chat/issues)?

**Comment by MartinSchoeler** [comment]
@mrminecart Please follow @MarcosSpessatto instructions. Thanks!
