### ISSUE TITLE
Hold persistent data in a webhook

### ISSUE THREAD

**Issue by DominikGri** [RocketChat/docs-old#9]
I try to hold persistent data in a webhook. Is there a common solution, already ?

Actually I hold it in an array in the script header. But after every server restart the known states are gone.

**Comment by engelgabriel** [comment]
Not yet, but @rodrigok is working on that, using MongoDB.

**Comment by DominikGri** [comment]
Ok, i will wait for it.
Thanks for your replay.

**Comment by MartinSchoeler** [comment]
@rodrigok any updates?

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates
