### ISSUE TITLE
Slackbridge Documentation Outdated / Unclear

### ISSUE THREAD

**Issue by lithium-ap** [RocketChat/docs-old#907]
The slackbridge documentation is outdated. The creation of the bot for the uninitiated is unclear as well. Attempts to integrate using information provided were unsuccessful. 

I'll try to document a new process and provide an update if successful.

**Comment by MartinSchoeler** [comment]
@lithium-ap Thanks for the feedback, if you manage to write some documentation, even if it's not complete, please open a pr, if it's not complete I can finish it. Thanks!
