### ISSUE TITLE
Display bug, document outline sidebar overlaps content

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/docs-old#910]
As shown...

<img width="1456" alt="screenshot 2018-09-10 22 15 21" src="https://user-images.githubusercontent.com/1774379/45297017-4b928880-b547-11e8-9e40-370db28a998a.png">

**Comment by isabellarussell** [comment]
Same! Was about to post an issue about this but I saw this in time!
Looks very similar on mine too:
![image](https://user-images.githubusercontent.com/36157246/45299623-0dc04080-b504-11e8-8e6c-377e97ed8bdb.png)
