### ISSUE TITLE
MD breakpoint display error

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/docs-old#917]
At a certain breakpoint the page content is show below the menu, so you have to scroll for miles to see anything...

<img width="1440" alt="screenshot 2018-09-18 15 21 55 2" src="https://user-images.githubusercontent.com/1774379/45665985-efd38b00-bb56-11e8-8375-0737c955712f.png">

...

<img width="1440" alt="screenshot 2018-09-18 15 22 21 2" src="https://user-images.githubusercontent.com/1774379/45665991-f6620280-bb56-11e8-8495-5c94b9195877.png">

**Comment by Rodriq** [comment]
@MartinSchoeler Please this issue already has an updated fix. I recommend it's closure.
Here's the today's' page

![issues-917-BreakpointOKAY](https://user-images.githubusercontent.com/39289592/54472119-878efa80-47c3-11e9-91d0-66064b9618b8.png)
