### ISSUE TITLE
right table of contents cut off/spill over

### ISSUE THREAD

**Issue by isabellarussell** [RocketChat/docs-old#919]
The right hand table of contents is being cut on this doc https://rocket.chat/docs/developer-guides/iframe-integration/authentication/#google

![image](https://user-images.githubusercontent.com/36157246/45818191-e7a35900-bcd8-11e8-9b31-515e41c200bf.png)

**Comment by Rodriq** [comment]
@isabellarussell @MartinSchoeler Plese I think this issue should be closed. The doc has been updated with the fix already. Check to verify.

**Comment by MartinSchoeler** [comment]
Yes, this can be closed!
