### ISSUE TITLE
The documentation of the <User Create> REST API endpoint contains error (password argument is incorrect)

### ISSUE THREAD

**Issue by sawo** [RocketChat/docs-old#925]
I think the following page contains an issue: [https://rocket.chat/docs/developer-guides/rest-api/users/create/](https://rocket.chat/docs/developer-guides/rest-api/users/create/)

When providing the password for a user, the argument in the JSON object should be 'pass' instead of 'password'.

My RocketChat version is  0.69.1

**Comment by MarcosSpessatto** [comment]
Hi @sawo, as [you can see in the codebase](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/users.js#L9), the correct parameter is `password`. The http call with the `password` parameter, is returning an error for you?

**Comment by sawo** [comment]
Hi @MarcosSpessatto, you are right. I was mixing it with the [users/register function ](https://rocket.chat/docs/developer-guides/rest-api/users/register/), where the argument for providing password is 'pass'.
