### ISSUE TITLE
wss://mydomain/websocket is not working

### ISSUE THREAD

**Issue by ashokj82** [RocketChat/docs-old#930]
I am trying connect with wss and want to use LiveChat API. Can someone help how to enable it on ubuntu server? I have one VM on Azure and installed rocket chat using snap.

Please help.

**Comment by renatobecker-zz** [comment]
Hi @ashokj82, Please take a look at our Realtime API documentation:
https://rocket.chat/docs/developer-guides/realtime-api/

Here you'll find the documentation related to Livechat Realtime API:
https://rocket.chat/docs/developer-guides/realtime-api/livechat-api/
