### ISSUE TITLE
Match failed error

### ISSUE THREAD

**Issue by ashokj82** [RocketChat/docs-old#934]
Exception while invoking method 'sendMessageLivechat' Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation     at check (/snap/rocketchat-server/1324/programs/server/packages/check.js:68:17)     at MethodInvocation.sendMessageLivechat (/snap/rocketchat-server/1324/programs/server/packages/rocketchat_livechat.js:1825:5)     at MethodInvocation.methodsMap.(anonymous function) (/snap/rocketchat-server/1324/programs/server/packages/rocketchat_lib.js:2496:36)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (/snap/rocketchat-server/1324/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/snap/rocketchat-server/1324/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/snap/rocketchat-server/1324/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/snap/rocketchat-server/1324/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/snap/rocketchat-server/1324/programs/server/packages/ddp-server.js:875:23)     at /snap/rocketchat-server/1324/programs/server/packages/ddp-server.js:754:85  
[34mI20181003-08:11:29.040(0) Sanitized and reported to the client as: Match failed [400] 
[34mI20181003-08:11:29.040(0) undefined undefined

**Comment by localguru** [comment]
docs? More infos like RC version etc.

**Comment by ashokj82** [comment]
There was a problem with sendMessageLivechat method call. As per documentation last parameter is "Id" but it is actually agnet info if you are dealing with guest user. Method should be called as

 this.realTimeAPI.callMethod("sendMessageLivechat", { "_id": "random string", "rid": "Random string", "msg": "test", "token": "guest token"}, {
                      "agentId": this.agentId,
                      "username": this.agentUserName
                    }).subscribe(
                      (res) => {});
