### ISSUE TITLE
Upgrade procedure for Multiple Instances on multiple nodes

### ISSUE THREAD

**Issue by pkolmann** [RocketChat/docs-old#935]
I have used the guide at 

https://github.com/RocketChat/docs/tree/master/installation/manual-installation/multiple-instances-to-improve-performance

to build a multi-instance multi-host rocketChat Service. What I am missing is a guide how to upgrade this multi node cluster.

Can you do an in place upgrade and keep stuff running? Do you need to schedule a downtime, take all nodes offline, update everything and start everything up again?

Please advise and add to https://github.com/RocketChat/docs/tree/master/installation/manual-installation/multiple-instances-to-improve-performance

Thanks
Philipp

**Comment by Rodriq** [comment]
One of the ways is to perform on the full cluster. This is not mentioned explicitly, check the docs https://docs.rocket.chat/quick-start/scaling-rocket.chat
