### ISSUE TITLE
Email Verification & Use DNS Domain Check

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/docs-old#94]
Document email verification option, as well as the Use DNS Domain Check

By default "Use DNS Domain Check" is on.  And "Email Verification" when turned on, will not allow people to register if they are not using a valid email domain.

**Comment by engelgabriel** [comment]
I think it should be FALSE by default.

**Comment by engelgabriel** [comment]
Or, the first ADMIN should bypass the rule.

**Comment by geekgonecrazy** [comment]
This mainly has come up when people are doing slack imports.  I just wanted to add a note so I remember to document that behavior somewhere.

**Comment by engelgabriel** [comment]
Lets make it default false for now.
