### ISSUE TITLE
separate document for mongodb replicaset instead of redirecting to medium article

### ISSUE THREAD

**Issue by Sagar2366** [RocketChat/docs-old#981]
Instead of forwarding to medium article (https://medium.com/@ManagedKube/deploy-a-mongodb-cluster-in-steps-9-using-docker-49205e231319) and even if someone follows this article it needs a lot of chnages to made according to requirement, which is not everyone could understand. So it would be great If we can have a separate documentation for this.

**Comment by Rodriq** [comment]
You are correct. the docs for MongoDB replicaset can be found here https://docs.rocket.chat/quick-start/installing-and-updating/other-deployment-methods/manual-installation/extras/mongo-replicas
