### ISSUE TITLE
Email whit users.list

### ISSUE THREAD

**Issue by PabloBaamonde** [RocketChat/docs-old#990]
The users.list command returns the user's email value, when logged in as administrator. I wanted to take the email field with a normal user.
This is possible?

**Comment by thayannevls** [comment]
Yes @PabloBaamonde. You can [authenticate](https://rocket.chat/docs/developer-guides/rest-api/authentication/login/) as a normal user and use their `authToken` and `userId` on [`users.list`](https://rocket.chat/docs/developer-guides/rest-api/users/list/).

**Comment by MarcosSpessatto** [comment]
@PabloBaamonde you can't, unless the user has the `view-full-other-user-info` permission.
