### ISSUE TITLE
add margin left to links on docs cards on home

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/docs-old#997]
![image](https://user-images.githubusercontent.com/1000217/48866630-a30c6a80-edba-11e8-9e6f-2e5676db3c67.png)

**Comment by Rodriq** [comment]
Hey @engelgabriel @MartinSchoeler  Noticed this issue has been idle for a while.
  Do you mind assigning over to me?

**Comment by MartinSchoeler** [comment]
Not applicable with gitbook
